// Chef Profile Page - View and edit chef profile with photo upload (MAI-921) + Reviews display (MAI-1013) + Signature Dishes (MAI-1047)

import { db } from '../db/index.js';
import { users, chefProfiles } from '../db/schema.js';
import { eq } from 'drizzle-orm';

declare var currentChef: any;
export default function buildChefProfilePage(chefId?: number): string {
  // If chefId provided, fetch that chef's profile (public view)
  // Otherwise, show the profile editor (chef-only)
  const isPublicView = chefId !== undefined;
  
  var html = '';
  html += '<!DOCTYPE html>\n';
  html += '<html lang="en">\n';
  html += '<head>\n';
  html += '<meta charset="UTF-8">\n';
  html += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  html += '<title>Chef Profile | Maison des Chefs</title>\n';
  html += '<style>\n';
  html += '    * { margin: 0; padding: 0; box-sizing: border-box; }\n';
  html += '    body { font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f8f9fa; }\n';
  html += '    nav { position: fixed; top: 0; left: 0; right: 0; background: rgba(0,0,0,0.9); padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; z-index: 100; backdrop-filter: blur(10px); }\n';
  html += '    nav .logo { color: white; font-size: 1.5rem; font-weight: bold; text-decoration: none; }\n';
  html += '    nav .nav-links { display: flex; gap: 1.5rem; }\n';
  html += '    nav .nav-links a { color: white; text-decoration: none; transition: opacity 0.3s; }\n';
  html += '    nav .nav-links a:hover { opacity: 0.8; }\n';
  html += '    .page-header { background: linear-gradient(135deg, #2c3e50 0%, #1a252f 100%); padding: 6rem 2rem 2.5rem; color: white; text-align: center; }\n';
  html += '    .page-header h1 { font-size: clamp(1.8rem, 4vw, 2.5rem); margin-bottom: 0.5rem; }\n';
  html += '    .page-header p { opacity: 0.9; font-size: 1rem; }\n';
  html += '    .profile-container { max-width: 700px; margin: 2rem auto; padding: 0 2rem; }\n';
  html += '    .profile-card { background: white; border-radius: 12px; padding: 2rem; box-shadow: 0 2px 8px rgba(0,0,0,0.06); margin-bottom: 1.5rem; }\n';
  html += '    .profile-header { display: flex; align-items: center; gap: 1.5rem; margin-bottom: 2rem; padding-bottom: 1.5rem; border-bottom: 1px solid #eee; }\n';
  html += '    .photo-section { position: relative; }\n';
  html += '    .chef-photo { width: 120px; height: 120px; border-radius: 50%; object-fit: cover; border: 4px solid #fff; box-shadow: 0 4px 12px rgba(0,0,0,0.15); }\n';
  html += '    .chef-photo-placeholder { width: 120px; height: 120px; border-radius: 50%; background: #c9a227; color: white; display: flex; align-items: center; justify-content: center; font-size: 2.5rem; font-weight: 700; border: 4px solid #fff; box-shadow: 0 4px 12px rgba(0,0,0,0.15); }\n';
  html += '    .photo-upload-btn { position: absolute; bottom: 0; right: 0; background: #c9a227; color: white; border: none; border-radius: 50%; width: 36px; height: 36px; cursor: pointer; display: flex; align-items: center; justify-content: center; font-size: 1.2rem; transition: background 0.2s; }\n';
  html += '    .photo-upload-btn:hover { background: #b8922a; }\n';
  html += '    .photo-upload-btn:disabled { background: #ccc; cursor: not-allowed; }\n';
  html += '    .profile-info h2 { font-size: 1.5rem; color: #2c3e50; margin-bottom: 0.25rem; }\n';
  html += '    .profile-info .location { color: #666; font-size: 0.95rem; margin-bottom: 0.5rem; }\n';
  html += '    .profile-info .rating-badge { display: inline-flex; align-items: center; gap: 0.3rem; background: #fff8e1; color: #f57c00; padding: 0.3rem 0.7rem; border-radius: 20px; font-size: 0.9rem; font-weight: 600; margin-left: 0.5rem; }\n';
  html += '    .verified-badge { display: inline-flex; align-items: center; gap: 0.25rem; background: #e8f5e9; color: #2e7d32; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.8rem; font-weight: 600; }\n';
  html += '    .form-group { margin-bottom: 1.25rem; }\n';
  html += '    .form-group label { display: block; font-weight: 500; color: #555; margin-bottom: 0.4rem; font-size: 0.9rem; }\n';
  html += '    .form-group input[type="text"], .form-group input[type="number"], .form-group textarea { width: 100%; padding: 0.75rem; border: 1px solid #ddd; border-radius: 6px; font-size: 0.95rem; font-family: inherit; }\n';
  html += '    .form-group textarea { resize: vertical; min-height: 100px; }\n';
  html += '    .btn { display: inline-block; background: #c9a227; color: white; padding: 0.75rem 1.5rem; text-decoration: none; border-radius: 4px; font-weight: 600; transition: background 0.2s; border: none; cursor: pointer; font-size: 0.95rem; }\n';
  html += '    .btn:hover { background: #b8922a; }\n';
  html += '    .btn-secondary { background: #6c757d; }\n';
  html += '    .btn-secondary:hover { background: #5a6268; }\n';
  html += '    .btn-sm { padding: 0.4rem 0.9rem; font-size: 0.85rem; }\n';
  html += '    .btn-danger { background: #c0392b; }\n';
  html += '    .btn-danger:hover { background: #a93226; }\n';
  html += '    .error-msg { background: #f8d7da; color: #721c24; padding: 0.75rem 1rem; border-radius: 6px; margin-bottom: 1rem; font-size: 0.9rem; display: none; }\n';
  html += '    .success-msg { background: #d4edda; color: #155724; padding: 0.75rem 1rem; border-radius: 6px; margin-bottom: 1rem; font-size: 0.9rem; display: none; }\n';
  html += '    .loading-state, .error-state, .auth-prompt { text-align: center; padding: 4rem 2rem; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }\n';
  html += '    .loading-state .spinner { width: 48px; height: 48px; border: 4px solid #f3f3f3; border-top: 4px solid #c9a227; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 1rem; }\n';
  html += '    @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }\n';
  html += '    .auth-prompt h2 { margin-bottom: 0.5rem; color: #2c3e50; }\n';
  html += '    .auth-prompt p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    footer { background: #1a1a1a; color: white; padding: 2rem; text-align: center; margin-top: 4rem; }\n';
  html += '    footer .logo { font-size: 1.3rem; font-weight: bold; margin-bottom: 0.5rem; }\n';
  html += '    footer p { opacity: 0.7; font-size: 0.85rem; }\n';
  html += '    .hidden { display: none !important; }\n';
  html += '    /* Reviews section styles (MAI-1013) */\n';
  html += '    .reviews-section { margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid #eee; }\n';
  html += '    .reviews-header { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 1.5rem; flex-wrap: wrap; gap: 1rem; }\n';
  html += '    .reviews-rating-big { font-size: 2.5rem; font-weight: 700; color: #2c3e50; line-height: 1; margin-bottom: 0.25rem; }\n';
  html += '    .reviews-meta { display: flex; flex-direction: column; gap: 0.25rem; }\n';
  html += '    .reviews-stars-big { color: #ffc107; font-size: 1.2rem; letter-spacing: 2px; }\n';
  html += '    .reviews-count { color: #888; font-size: 0.85rem; }\n';
  html += '    .reviews-list { list-style: none; }\n';
  html += '    .review-item { padding: 1rem 0; border-bottom: 1px solid #f0f0f0; }\n';
  html += '    .review-item:last-child { border-bottom: none; }\n';
  html += '    .review-header { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.5rem; flex-wrap: wrap; }\n';
  html += '    .review-stars { color: #ffc107; font-size: 0.95rem; letter-spacing: 1px; }\n';
  html += '    .review-author { font-weight: 600; color: #2c3e50; font-size: 0.95rem; }\n';
  html += '    .review-date { color: #999; font-size: 0.85rem; }\n';
  html += '    .review-comment { color: #555; font-size: 0.9rem; line-height: 1.5; margin-top: 0.25rem; }\n';
  html += '    /* Signature dishes styles (MAI-1047) */\n';
  html += '    .signature-dishes-section { margin-top: 1.5rem; padding-top: 1.5rem; border-top: 1px solid #eee; }\n';
  html += '    .signature-dishes-header { display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1rem; }\n';
  html += '    .signature-dishes-header h3 { font-size: 1.1rem; color: #2c3e50; }\n';
  html += '    .signature-dishes-list { list-style: none; }\n';
  html += '    .signature-dish-item { padding: 0.75rem 0; border-bottom: 1px solid #f0f0f0; }\n';
  html += '    .signature-dish-item:last-child { border-bottom: none; }\n';
  html += '    .signature-dish-name { font-weight: 600; color: #2c3e50; font-size: 1rem; margin-bottom: 0.25rem; }\n';
  html += '    .signature-dish-description { color: #666; font-size: 0.9rem; line-height: 1.4; }\n';
  html += '    .dish-entry { margin-bottom: 1rem; padding: 1rem; background: #f8f9fa; border-radius: 8px; }\n';
  html += '    .dish-entry input, .dish-entry textarea { margin-bottom: 0.5rem; }\n';
  html += '    .dish-entry:last-child { margin-bottom: 0; }\n';
  html += '    .section-hint { font-size: 0.85rem; color: #888; font-weight: 400; }\n';
  html += '    @media (max-width: 768px) { .profile-header { flex-direction: column; text-align: center; } .reviews-header { flex-direction: column; align-items: flex-start; } }\n';
  html += '  </style>\n';
  html += '</head>\n';
  html += '<body>\n';
  html += '<nav><a href="/" class="logo">Maison des Chefs</a><div class="nav-links"><a href="/chef/leads">My Leads</a><a href="/chefs">Browse Chefs</a><a href="/auth/login">Sign In</a></div></nav>\n';
  html += '<section class="page-header"><div><h1>Chef Profile</h1><p>Manage your public chef profile</p></div></section>\n';
  html += '<div class="profile-container">\n';
  html += '<div id="loadingState" class="loading-state"><div class="spinner"></div><p>Loading profile...</p></div>\n';
  html += '<div id="authPrompt" class="auth-prompt" style="display:none"><h2>Sign In Required</h2><p>Please sign in to manage your chef profile.</p><a href="/auth/login" class="btn">Sign In</a></div>\n';
  html += '<div id="errorState" class="error-state" style="display:none"><h2>Something went wrong</h2><p id="errorMessage">Unable to load profile.</p></div>\n';
  html += '<div id="profileContent" class="profile-card hidden"></div>\n';
  html += '</div>\n';
  html += '<footer><div class="logo">Maison des Chefs</div><p>&copy; 2026 Maison des Chefs. All rights reserved.</p></footer>\n';
  html += '<script>\n';
  html += '    var API_BASE = \'\';\n';
  html += '    var currentChef = null;\n';
  html += '    var uploadedPhotoUrl = null;\n';
  html += '    var chefUserId = null;\n';
  html += '    \n';
  html += '    function escapeHtml(text) { if (!text) return \'\'; var div = document.createElement(\'div\'); div.textContent = text; return div.innerHTML; }\n';
  html += '    \n';
  html += '    function getInitials(name) { if (!name) return \'?\'; return name.split(\' \').map(n => n[0]).join(\'\').toUpperCase().substring(0, 2); }\n';
  html += '    \n';
  html += '    function showError(message) { var el = document.getElementById(\'errorMsg\'); if (el) { el.textContent = message; el.style.display = \'block\'; } }\n';
  html += '    \n';
  html += '    function showSuccess(message) { var el = document.getElementById(\'successMsg\'); if (el) { el.textContent = message; el.style.display = \'block\'; setTimeout(function() { el.style.display = \'none\'; }, 3000); } }\n';
  html += '    \n';
  html += '    function formatDate(dateStr) { if (!dateStr) return \'\'; var date = new Date(dateStr); var now = new Date(); var diffMs = now - date; var diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24)); if (diffDays === 0) return \'Today\'; if (diffDays === 1) return \'Yesterday\'; if (diffDays < 7) return diffDays + \' days ago\'; if (diffDays < 30) return Math.floor(diffDays / 7) + \' weeks ago\'; if (diffDays < 365) return Math.floor(diffDays / 30) + \' months ago\'; return Math.floor(diffDays / 365) + \' years ago\'; }\n';
  html += '    \n';
  html += '    function renderStars(rating) { var stars = \'\'; for (var i = 1; i <= 5; i++) { stars += i <= rating ? \'★\' : \'☆\'; } return stars; }\n';
  html += '    \n';
  html += '    function renderReviews(reviewsData) { if (!reviewsData || reviewsData.reviewCount === 0) return \'\'; var html = \'<div class="reviews-section">\'; html += \'<div class="reviews-header">\'; html += \'<div class="reviews-meta">\'; html += \'<div class="reviews-rating-big">\' + escapeHtml(String(reviewsData.avgRating)) + \'</div>\'; html += \'<div class="reviews-stars-big">\' + renderStars(Math.round(reviewsData.avgRating)) + \'</div>\'; html += \'<div class="reviews-count">\' + reviewsData.reviewCount + \' \' + (reviewsData.reviewCount === 1 ? \'review\' : \'reviews\') + \'</div>\'; html += \'</div>\' html += \'</div>\'; if (reviewsData.reviews && reviewsData.reviews.length > 0) { html += \'<ul class="reviews-list">\'; reviewsData.reviews.forEach(function(r) { html += \'<li class="review-item">\'; html += \'<div class="review-header">\'; html += \'<span class="review-stars">\' + renderStars(r.rating) + \'</span>\'; html += \'<span class="review-author">\' + escapeHtml(r.dinerFirstName || \'Verified Diner\') + \'</span>\'; html += \'<span class="review-date">\' + formatDate(r.createdAt) + \'</span>\'; html += \'</div>\'; if (r.comment) { html += \'<p class="review-comment">\' + escapeHtml(r.comment) + \'</p>\'; } html += \'</li>\'; }); html += \'</ul>\'; } } html += \'</div>\'; return html; }\n';
  html += '    \n';
  html += '    function renderSignatureDishesDisplay(signatureDishes) { if (!signatureDishes || signatureDishes.length === 0) return \'\'; var html = \'<div class="signature-dishes-section">\'; html += \'<div class="signature-dishes-header">\'; html += \'<h3>Signature Dishes</h3>\'; html += \'</div>\'; html += \'<ul class="signature-dishes-list">\'; signatureDishes.forEach(function(dish) { if (dish.name) { html += \'<li class="signature-dish-item">\'; html += \'<div class="signature-dish-name\">\' + escapeHtml(dish.name) + \'</div>\'; if (dish.description) { html += \'<div class="signature-dish-description\">\' + escapeHtml(dish.description) + \'</div>\'; } html += \'</li>\'; } }); html += \'</ul>\'; html += \'</div>\'; return html; }\n';
  html += '    \n';
  html += '    function renderProfile(chef) {\n';
  html += '      currentChef = chef;\n';
  html += '      chefUserId = chef.id;\n';
  html += '      var photoHtml = \'\';\n';
  html += '      if (chef.photoUrl) {\n';
  html += '        photoHtml = \'<img src="\' + escapeHtml(chef.photoUrl) + \'" alt="\' + escapeHtml(chef.name) + \'" class="chef-photo">\';\n';
  html += '      } else {\n';
  html += '        photoHtml = \'<div class="chef-photo-placeholder">\' + getInitials(chef.name) + \'</div>\';\n';
  html += '      }\n';
  html += '      var verifiedHtml = chef.verified ? \'<span class="verified-badge\">✓ Verified Chef</span>\' : \'\';\n';
  html += '      var html = \'<div class="profile-header">\';\n';
  html += '        html += \'<div class="photo-section">\';\n';
  html += '          html += photoHtml;\n';
  html += '          html += \'<button class="photo-upload-btn" id="photoUploadBtn" title="Change photo" onclick="document.getElementById(\\\'photoInput\\\').click()">📷</button>\';\n';
  html += '          html += \'<input type="file" id="photoInput" accept="image/jpeg,image/png,image/webp" style="display:none" onchange="handlePhotoSelect(this)">\';\n';
  html += '        html += \'</div>\';\n';
  html += '        html += \'<div class="profile-info">\';\n';
  html += '          html += \'<h2>\' + escapeHtml(chef.name) + \'</h2>\';\n';
  html += '          html += \'<p class="location\">📍 \' + escapeHtml(chef.location || \'Location not set\') + \'</p>\';\n';
  html += '          html += verifiedHtml;\n';
  html += '        html += \'</div>\';\n';
  html += '      html += \'</div>\';\n';
  html += '      html += \'<div id="errorMsg" class="error-msg"></div>\';\n';
  html += '      html += \'<div id="successMsg" class="success-msg"></div>\';\n';
  html += '      html += \'<form id="profileForm" onsubmit="saveProfile(event)">\';\n';
  html += '        html += \'<div class="form-group">\';\n';
  html += '          html += \'<label for="bio">Bio</label>\';\n';
  html += '          html += \'<textarea id="bio" name="bio" placeholder="Tell diners about yourself and your culinary style...">\' + escapeHtml(chef.bio || \'\') + \'</textarea>\';\n';
  html += '        html += \'</div>\';\n';
  html += '        html += \'<div class="form-group">\';\n';
  html += '          html += \'<label for="location">Location</label>\';\n';
  html += '          html += \'<input type="text" id="location" name="location" placeholder="e.g., Montreal, QC" value="\' + escapeHtml(chef.location || \'\') + \'">\';\n';
  html += '        html += \'</div>\';\n';
  html += '        html += \'<div class="form-group">\';\n';
  html += '          html += \'<label>Signature Dishes <span class="section-hint">(up to 3)</span></label>\';\n';
  html += '          html += \'<div id="signatureDishesContainer">\';\n';
  // @ts-ignore
  var dishes = (currentChef || {}).signatureDishes || [];
  for (var d = 0; d < 3; d++) {
    var dish = dishes[d] || { name: '', description: '' };
    html += '            <div class="dish-entry">';
    html += '              <input type="text" name="dishName' + d + '" placeholder="Dish name" maxlength="100" value="\' + escapeHtml(dish.name || \'\') + \'">';
    html += '              <textarea name="dishDesc' + d + '" placeholder="Short description..." maxlength="500" rows="2">\' + escapeHtml(dish.description || \'\') + \'</textarea>';
    html += '            </div>';
  }
  html += '          </div>\';\n';
  html += '        html += \'</div>\';\n';
  html += '        html += \'<button type="submit" class="btn" id="saveBtn">Save Profile</button>\';\n';
  html += '        html += \' <button type="button" class="btn btn-secondary" onclick="loadProfile()">Cancel</button>\';\n';
  html += '      html += \'</form>\';\n';
  html += '      html += \'<div id="reviewsContainer"></div>\';\n';
  html += '      document.getElementById(\'profileContent\').innerHTML = html;\n';
  html += '      document.getElementById(\'profileContent\').classList.remove(\'hidden\');\n';
  html += '      loadChefReviews();\n';
  html += '    }\n';
  html += '    \n';
  html += '    async function loadChefReviews() { if (!chefUserId) return; try { var response = await fetch(API_BASE + \'/api/chefs/\' + chefUserId + \'/reviews\'); if (!response.ok) return; var data = await response.json(); var container = document.getElementById(\'reviewsContainer\'); if (container) { container.innerHTML = renderReviews(data); } } catch (err) { console.error(\'Error loading reviews:\', err); } }\n';
  html += '    \n';
  html += '    function handlePhotoSelect(input) {\n';
  html += '      if (!input.files || !input.files[0]) return;\n';
  html += '      var file = input.files[0];\n';
  html += '      var validTypes = [\'image/jpeg\',\'image/png\',\'image/webp\'];\n';
  html += '      if (!validTypes.includes(file.type)) {\n';
  html += '        showError(\'Please upload a JPG, PNG, or WebP image.\');\n';
  html += '        input.value = \'\';\n';
  html += '        return;\n';
  html += '      }\n';
  html += '      if (file.size > 5 * 1024 * 1024) {\n';
  html += '        showError(\'File too large. Maximum 5MB allowed.\');\n';
  html += '        input.value = \'\';\n';
  html += '        return;\n';
  html += '      }\n';
  html += '      uploadPhoto(file);\n';
  html += '    }\n';
  html += '    \n';
  html += '    async function uploadPhoto(file) {\n';
  html += '      var btn = document.getElementById(\'photoUploadBtn\');\n';
  html += '      btn.disabled = true;\n';
  html += '      btn.textContent = \'⏳\';\n';
  html += '      var errorMsg = document.getElementById(\'errorMsg\');\n';
  html += '      errorMsg.style.display = \'none\';\n';
  html += '      \n';
  html += '      var formData = new FormData();\n';
  html += '      formData.append(\'photo\', file);\n';
  html += '      \n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        var response = await fetch(API_BASE + \'/api/chef/photo\', {\n';
  html += '          method: \'POST\',\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token },\n';
  html += '          body: formData\n';
  html += '        });\n';
  html += '        \n';
  html += '        if (response.status === 401) {\n';
  html += '          document.getElementById(\'profileContent\').classList.add(\'hidden\');\n';
  html += '          document.getElementById(\'authPrompt\').style.display = \'block\';\n';
  html += '          return;\n';
  html += '        }\n';
  html += '        \n';
  html += '        var data = await response.json();\n';
  html += '        \n';
  html += '        if (!response.ok) {\n';
  html += '          showError(data.error || \'Upload failed. Please try again.\');\n';
  html += '          btn.disabled = false;\n';
  html += '          btn.textContent = \'📷\';\n';
  html += '          return;\n';
  html += '        }\n';
  html += '        \n';
  html += '        uploadedPhotoUrl = data.photoUrl;\n';
  html += '        var photoSection = document.querySelector(\'.photo-section\');\n';
  html += '        var img = document.createElement(\'img\');\n';
  html += '        img.src = data.photoUrl;\n';
  html += '        img.alt = currentChef.name;\n';
  html += '        img.className = \'chef-photo\';\n';
  html += '        var placeholder = photoSection.querySelector(\'.chef-photo-placeholder\');\n';
  html += '        if (placeholder) placeholder.remove();\n';
  html += '        var oldImg = photoSection.querySelector(\'.chef-photo\');\n';
  html += '        if (oldImg) oldImg.remove();\n';
  html += '        photoSection.insertBefore(img, photoSection.firstChild);\n';
  html += '        showSuccess(\'Photo uploaded successfully!\');\n';
  html += '        btn.disabled = false;\n';
  html += '        btn.textContent = \'📷\';\n';
  html += '      } catch (err) {\n';
  html += '        console.error(\'Photo upload error:\', err);\n';
  html += '        showError(\'Upload failed. Please try again.\');\n';
  html += '        btn.disabled = false;\n';
  html += '        btn.textContent = \'📷\';\n';
  html += '      }\n';
  html += '    }\n';
  html += '    \n';
  html += '    function collectSignatureDishes() {\n';
  html += '      var dishes = [];\n';
  html += '      for (var i = 0; i < 3; i++) {\n';
  html += '        var nameInput = document.getElementById(\'profileForm\').querySelector(\'[name="dishName\' + i + \'"]\');\n';
  html += '        var descInput = document.getElementById(\'profileForm\').querySelector(\'[name="dishDesc\' + i + \'"]\');\n';
  html += '        if (nameInput && nameInput.value.trim()) {\n';
  html += '          dishes.push({ name: nameInput.value.trim(), description: (descInput && descInput.value.trim()) || \'\' });\n';
  html += '        }\n';
  html += '      }\n';
  html += '      return dishes;\n';
  html += '    }\n';
  html += '    \n';
  html += '    async function saveProfile(e) {\n';
  html += '      e.preventDefault();\n';
  html += '      var btn = document.getElementById(\'saveBtn\');\n';
  html += '      btn.disabled = true;\n';
  html += '      btn.textContent = \'Saving...\';\n';
  html += '      var errorMsg = document.getElementById(\'errorMsg\');\n';
  html += '      errorMsg.style.display = \'none\';\n';
  html += '      \n';
  html += '      var bio = document.getElementById(\'bio\').value;\n';
  html += '      var location = document.getElementById(\'location\').value;\n';
  html += '      var signatureDishes = collectSignatureDishes();\n';
  html += '      \n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        var response = await fetch(API_BASE + \'/api/chefs/profile\', {\n';
  html += '          method: \'POST\',\n';
  html += '          headers: {\n';
  html += '            \'Authorization\': \'Bearer \' + token,\n';
  html += '            \'Content-Type\': \'application/json\'\n';
  html += '          },\n';
  html += '          body: JSON.stringify({ bio: bio, location: location, signatureDishes: signatureDishes })\n';
  html += '        });\n';
  html += '        \n';
  html += '        if (response.status === 401) {\n';
  html += '          document.getElementById(\'profileContent\').classList.add(\'hidden\');\n';
  html += '          document.getElementById(\'authPrompt\').style.display = \'block\';\n';
  html += '          return;\n';
  html += '        }\n';
  html += '        \n';
  html += '        if (!response.ok) {\n';
  html += '          var data = await response.json();\n';
  html += '          showError(data.error || \'Failed to save profile.\');\n';
  html += '          btn.disabled = false;\n';
  html += '          btn.textContent = \'Save Profile\';\n';
  html += '          return;\n';
  html += '        }\n';
  html += '        \n';
  html += '        var data = await response.json();\n';
  html += '        currentChef = data;\n';
  html += '        showSuccess(\'Profile saved successfully!\');\n';
  html += '        btn.disabled = false;\n';
  html += '        btn.textContent = \'Save Profile\';\n';
  html += '      } catch (err) {\n';
  html += '        console.error(\'Save profile error:\', err);\n';
  html += '        showError(\'Failed to save profile. Please try again.\');\n';
  html += '        btn.disabled = false;\n';
  html += '        btn.textContent = \'Save Profile\';\n';
  html += '      }\n';
  html += '    }\n';
  html += '    \n';
  html += '    async function loadProfile() {\n';
  html += '      var loading = document.getElementById(\'loadingState\');\n';
  html += '      var authPrompt = document.getElementById(\'authPrompt\');\n';
  html += '      var errorState = document.getElementById(\'errorState\');\n';
  html += '      var profileContent = document.getElementById(\'profileContent\');\n';
  html += '      \n';
  html += '      loading.style.display = \'block\';\n';
  html += '      authPrompt.style.display = \'none\';\n';
  html += '      errorState.style.display = \'none\';\n';
  html += '      profileContent.classList.add(\'hidden\');\n';
  html += '      \n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        if (!token) {\n';
  html += '          loading.style.display = \'none\';\n';
  html += '          authPrompt.style.display = \'block\';\n';
  html += '          return;\n';
  html += '        }\n';
  html += '        \n';
  html += '        var response = await fetch(API_BASE + \'/api/chefs/me/profile\', {\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token }\n';
  html += '        });\n';
  html += '        \n';
  html += '        if (response.status === 401) {\n';
  html += '          loading.style.display = \'none\';\n';
  html += '          authPrompt.style.display = \'block\';\n';
  html += '          return;\n';
  html += '        }\n';
  html += '        \n';
  html += '        if (!response.ok) {\n';
  html += '          throw new Error(\'Failed to fetch profile\');\n';
  html += '        }\n';
  html += '        \n';
  html += '        var chef = await response.json();\n';
  html += '        loading.style.display = \'none\';\n';
  html += '        renderProfile(chef);\n';
  html += '      } catch (err) {\n';
  html += '        console.error(\'Error loading profile:\', err);\n';
  html += '        loading.style.display = \'none\';\n';
  html += '        errorState.style.display = \'block\';\n';
  html += '        document.getElementById(\'errorMessage\').textContent = err.message || \'Unable to load profile.\';\n';
  html += '      }\n';
  html += '    }\n';
  html += '    \n';
  html += '    loadProfile();\n';
  html += '  </script>\n';
  html += '</body>\n';
  html += '</html>\n';
  return html;
}