// Chef Leads Dashboard Page (MAI-766)

export default function buildChefLeadsPage(): string {
  var html = '';
  html += '<!DOCTYPE html>\n';
  html += '<html lang="en">\n';
  html += '<head>\n';
  html += '<meta charset="UTF-8">\n';
  html += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  html += '<title>Lead Management | Chef Dashboard</title>\n';
  html += '<style>\n';
  html += '    * { margin: 0; padding: 0; box-sizing: border-box; }\n';
  html += '    body { font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f8f9fa; }\n';
  html += '    nav { position: fixed; top: 0; left: 0; right: 0; background: rgba(0,0,0,0.9); padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; z-index: 100; backdrop-filter: blur(10px); }\n';
  html += '    nav .logo { color: white; font-size: 1.5rem; font-weight: bold; text-decoration: none; }\n';
  html += '    nav .nav-links { display: flex; gap: 1.5rem; }\n';
  html += '    nav .nav-links a { color: white; text-decoration: none; transition: opacity 0.3s; }\n';
  html += '    nav .nav-links a:hover { opacity: 0.8; }\n';
  html += '    .page-header { background: linear-gradient(135deg, #2c3e50 0%, #1a252f 100%); padding: 7rem 2rem 2.5rem; color: white; }\n';
  html += '    .page-header-inner { max-width: 1100px; margin: 0 auto; display: flex; justify-content: space-between; align-items: center; }\n';
  html += '    .page-header h1 { font-size: clamp(1.8rem, 4vw, 2.5rem); margin-bottom: 0.3rem; }\n';
  html += '    .page-header p { opacity: 0.9; font-size: 1rem; }\n';
  html += '    .btn { display: inline-block; background: #c9a227; color: white; padding: 0.75rem 1.5rem; text-decoration: none; border-radius: 4px; font-weight: 600; transition: background 0.2s; border: none; cursor: pointer; font-size: 0.95rem; }\n';
  html += '    .btn:hover { background: #b8922a; }\n';
  html += '    .btn-secondary { background: #6c757d; }\n';
  html += '    .btn-secondary:hover { background: #5a6268; }\n';
  html += '    .btn-sm { padding: 0.4rem 0.9rem; font-size: 0.85rem; }\n';
  html += '    .btn-success { background: #27ae60; }\n';
  html += '    .btn-success:hover { background: #219a52; }\n';
  html += '    .btn-danger { background: #c0392b; }\n';
  html += '    .btn-danger:hover { background: #a93226; }\n';
  html += '    .leads-container { max-width: 1100px; margin: 2rem auto; padding: 0 2rem; }\n';
  html += '    .stats-row { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin-bottom: 2rem; }\n';
  html += '    .stat-card { background: white; padding: 1.25rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); text-align: center; }\n';
  html += '    .stat-value { font-size: 2rem; font-weight: 700; color: #2c3e50; }\n';
  html += '    .stat-label { font-size: 0.85rem; color: #888; margin-top: 0.25rem; }\n';
  html += '    .filter-bar { background: white; padding: 1rem 1.5rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); margin-bottom: 1.5rem; display: flex; gap: 1rem; align-items: center; flex-wrap: wrap; }\n';
  html += '    .filter-bar label { font-weight: 500; color: #555; font-size: 0.9rem; }\n';
  html += '    .filter-bar select { padding: 0.4rem 0.75rem; border: 1px solid #ddd; border-radius: 4px; font-size: 0.9rem; }\n';
  html += '    .leads-list { display: flex; flex-direction: column; gap: 1rem; }\n';
  html += '    .lead-card { background: white; padding: 1.25rem 1.5rem; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); cursor: pointer; transition: transform 0.15s, box-shadow 0.15s; display: flex; justify-content: space-between; align-items: center; gap: 1rem; }\n';
  html += '    .lead-card:hover { transform: translateY(-2px); box-shadow: 0 4px 16px rgba(0,0,0,0.1); }\n';
  html += '    .lead-card-main { flex: 1; }\n';
  html += '    .lead-card-header { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.4rem; flex-wrap: wrap; }\n';
  html += '    .lead-name { font-size: 1.1rem; font-weight: 600; color: #2c3e50; }\n';
  html += '    .lead-service { color: #666; font-size: 0.9rem; margin-bottom: 0.4rem; }\n';
  html += '    .lead-meta { display: flex; gap: 1rem; color: #888; font-size: 0.85rem; flex-wrap: wrap; }\n';
  html += '    .lead-meta span { display: flex; align-items: center; gap: 0.25rem; }\n';
  html += '    .lead-card-actions { display: flex; align-items: center; gap: 0.75rem; flex-shrink: 0; }\n';
  html += '    .status-badge { padding: 0.2rem 0.7rem; border-radius: 20px; font-size: 0.78rem; font-weight: 600; white-space: nowrap; }\n';
  html += '    .status-new { background: #e3f2fd; color: #1565c0; }\n';
  html += '    .status-responded { background: #fff3cd; color: #856404; }\n';
  html += '    .status-converted { background: #d4edda; color: #155724; }\n';
  html += '    .status-lost { background: #f8d7da; color: #721c24; }\n';
  html += '    .loading-state, .error-state, .empty-state, .auth-prompt { text-align: center; padding: 4rem 2rem; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }\n';
  html += '    .loading-state .spinner { width: 48px; height: 48px; border: 4px solid #f3f3f3; border-top: 4px solid #c9a227; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 1rem; }\n';
  html += '    @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }\n';
  html += '    .error-state { color: #c0392b; }\n';
  html += '    .error-state h2 { margin-bottom: 0.5rem; }\n';
  html += '    .error-state p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    .empty-state h2 { color: #2c3e50; margin-bottom: 0.5rem; }\n';
  html += '    .empty-state p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    .auth-prompt h2 { margin-bottom: 0.5rem; color: #2c3e50; }\n';
  html += '    .auth-prompt p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    .modal-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.6); z-index: 200; display: none; align-items: center; justify-content: center; padding: 1rem; }\n';
  html += '    .modal-overlay.open { display: flex; }\n';
  html += '    .modal { background: white; border-radius: 12px; width: 100%; max-width: 640px; max-height: 90vh; overflow-y: auto; box-shadow: 0 8px 32px rgba(0,0,0,0.2); }\n';
  html += '    .modal-header { padding: 1.5rem; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; align-items: flex-start; gap: 1rem; }\n';
  html += '    .modal-header h2 { font-size: 1.25rem; color: #2c3e50; }\n';
  html += '    .modal-close { background: none; border: none; font-size: 1.5rem; cursor: pointer; color: #888; padding: 0; line-height: 1; }\n';
  html += '    .modal-close:hover { color: #333; }\n';
  html += '    .modal-body { padding: 1.5rem; }\n';
  html += '    .modal-footer { padding: 1rem 1.5rem; border-top: 1px solid #eee; display: flex; justify-content: flex-end; gap: 0.75rem; }\n';
  html += '    .lead-detail-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }\n';
  html += '    .lead-detail-item { background: #f8f9fa; padding: 1rem; border-radius: 8px; }\n';
  html += '    .lead-detail-label { font-size: 0.8rem; color: #888; margin-bottom: 0.2rem; text-transform: uppercase; letter-spacing: 0.5px; }\n';
  html += '    .lead-detail-value { font-size: 1rem; font-weight: 600; color: #2c3e50; }\n';
  html += '    .lead-message { background: #f8f9fa; padding: 1rem; border-radius: 8px; margin-bottom: 1.5rem; }\n';
  html += '    .lead-message p { color: #555; font-size: 0.95rem; }\n';
  html += '    .quote-section { border-top: 2px solid #c9a227; padding-top: 1.5rem; margin-top: 1.5rem; }\n';
  html += '    .quote-section h3 { color: #2c3e50; margin-bottom: 1rem; }\n';
  html += '    .form-group { margin-bottom: 1rem; }\n';
  html += '    .form-group label { display: block; font-weight: 500; color: #555; margin-bottom: 0.4rem; font-size: 0.9rem; }\n';
  html += '    .form-group input, .form-group textarea { width: 100%; padding: 0.6rem 0.75rem; border: 1px solid #ddd; border-radius: 4px; font-size: 0.95rem; font-family: inherit; }\n';
  html += '    .form-group textarea { resize: vertical; min-height: 80px; }\n';
  html += '    .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }\n';
  html += '    .quote-preview { background: #fff9e6; border: 1px solid #c9a227; border-radius: 8px; padding: 1rem; margin-bottom: 1rem; font-size: 0.9rem; color: #555; }\n';
  html += '    .quote-preview strong { color: #2c3e50; }\n';
  html += '    .success-msg { background: #d4edda; color: #155724; padding: 0.75rem 1rem; border-radius: 6px; margin-bottom: 1rem; font-size: 0.9rem; }\n';
  html += '    footer { background: #1a1a1a; color: white; padding: 2rem; text-align: center; margin-top: 4rem; }\n';
  html += '    footer .logo { font-size: 1.3rem; font-weight: bold; margin-bottom: 0.5rem; }\n';
  html += '    footer p { opacity: 0.7; font-size: 0.85rem; }\n';
  html += '    @media (max-width: 768px) { .page-header-inner { flex-direction: column; align-items: flex-start; gap: 1rem; } .form-row { grid-template-columns: 1fr; } .lead-card { flex-direction: column; align-items: flex-start; } .lead-card-actions { width: 100%; justify-content: flex-end; } }\n';
  html += '  </style>\n';
  html += '</head>\n';
  html += '<body>\n';
  html += '<nav><a href="/" class="logo">Maison des Chefs</a><div class="nav-links"><a href="/chef/leads">My Leads</a><a href="/services">Services</a><a href="/auth/login">Sign In</a></div></nav>\n';
  html += '<section class="page-header"><div class="page-header-inner"><div><h1>Lead Management</h1><p>View and respond to diner inquiries</p></div></div></section>\n';
  html += '<div class="leads-container">\n';
  html += '<div class="stats-row" id="statsRow"><div class="stat-card"><div class="stat-value" id="statNew">-</div><div class="stat-label">New</div></div><div class="stat-card"><div class="stat-value" id="statResponded">-</div><div class="stat-label">Responded</div></div><div class="stat-card"><div class="stat-value" id="statConverted">-</div><div class="stat-label">Converted</div></div><div class="stat-card"><div class="stat-value" id="statLost">-</div><div class="stat-label">Lost</div></div></div>\n';
  html += '<div class="filter-bar"><label>Filter by status:</label><select id="statusFilter" onchange="renderLeads(currentLeads)"><option value="all">All Leads</option><option value="new">New</option><option value="responded">Responded</option><option value="converted">Converted</option><option value="lost">Lost</option></select></div>\n';
  html += '<div id="loadingState" class="loading-state"><div class="spinner"></div><p>Loading your leads...</p></div>\n';
  html += '<div id="authPrompt" class="auth-prompt" style="display:none"><h2>Sign In Required</h2><p>Please sign in to view your leads.</p><a href="/auth/login" class="btn">Sign In</a></div>\n';
  html += '<div id="errorState" class="error-state" style="display:none"><h2>Something went wrong</h2><p id="errorMessage">Unable to load leads.</p><button class="btn" onclick="loadLeads()">Try Again</button></div>\n';
  html += '<div id="emptyState" class="empty-state" style="display:none"><h2>No leads yet</h2><p>When diners inquire about your services, they will appear here.</p></div>\n';
  html += '<div id="leadsList" class="leads-list" style="display:none"></div>\n';
  html += '</div>\n';
  html += '<div class="modal-overlay" id="leadModal"><div class="modal"><div class="modal-header"><div><h2 id="modalLeadName">Lead Details</h2><span class="status-badge status-new" id="modalStatus"></span></div><button class="modal-close" onclick="closeModal()">&times;</button></div><div class="modal-body" id="modalBody"></div><div class="modal-footer" id="modalFooter"></div></div></div>\n';
  html += '<footer><div class="logo">Maison des Chefs</div><p>&copy; 2026 Maison des Chefs. All rights reserved.</p></footer>\n';
  html += '<script>\n';
  html += '    var API_BASE = \'\';\n';
  html += '    var currentLeads = [];\n';
  html += '    var currentLeadId = null;\n';
  html += '    function escapeHtml(text) { if (!text) return \'\'; var div = document.createElement(\'div\'); div.textContent = text; return div.innerHTML; }\n';
  html += '    function formatDate(dateStr) { if (!dateStr) return \'Flexible date\'; try { return new Date(dateStr).toLocaleDateString(\'en-US\', { month: \'short\', day: \'numeric\', year: \'numeric\' }); } catch(e) { return dateStr; } }\n';
  html += '    function formatEventDate(dateStr) { if (!dateStr) return \'Flexible\'; try { return new Date(dateStr).toLocaleDateString(\'en-US\', { weekday: \'short\', month: \'short\', day: \'numeric\', year: \'numeric\' }); } catch(e) { return dateStr; } }\n';
  html += '    function updateStats(leads) { var counts = { new: 0, responded: 0, converted: 0, lost: 0 }; for (var i = 0; i < leads.length; i++) { var s = leads[i].status; if (counts[s] !== undefined) counts[s]++; } document.getElementById(\'statNew\').textContent = counts.new; document.getElementById(\'statResponded\').textContent = counts.responded; document.getElementById(\'statConverted\').textContent = counts.converted; document.getElementById(\'statLost\').textContent = counts.lost; }\n';
  html += '    function renderLeadCard(lead) { var statusClass = \'status-\' + lead.status; var statusLabel = lead.status.charAt(0).toUpperCase() + lead.status.slice(1); var formattedDate = formatDate(lead.eventDate); var quoteInfo = \'\'; if (lead.status === \'responded\' && lead.quoteAmount) { quoteInfo = \' - Quoted $\' + Number(lead.quoteAmount).toFixed(0); } var guestCount = lead.guestCount || 0; var quoteInfoHtml = quoteInfo ? \'<span style="color:#27ae60;font-weight:500;">\' + quoteInfo + \'</span>\' : \'\'; return \'<div class="lead-card" onclick="openLeadDetail(\' + lead.id + \')">\' + \'<div class="lead-card-main">\' + \'<div class="lead-card-header">\' + \'<span class="lead-name">\' + escapeHtml(lead.clientName || \'Guest\') + \'</span>\' + \'<span class="status-badge \' + statusClass + \'">\' + statusLabel + \'</span>\' + \'</div>\' + \'<div class="lead-service">\' + escapeHtml(lead.serviceName || \'Service\') + \'</div>\' + \'<div class="lead-meta">\' + \'<span>\' + formattedDate + \'</span>\' + \'<span>\' + guestCount + \' guest\' + (guestCount !== 1 ? \'s\' : \'\') + \'</span>\' + \'<span>\' + escapeHtml(lead.email) + \'</span>\' + quoteInfoHtml + \'</div></div>\' + \'<div class="lead-card-actions"><button class="btn btn-sm" onclick="event.stopPropagation(); openLeadDetail(\' + lead.id + \')">View</button></div>\' + \'</div>\'; }\n';
  html += '    function renderLeads(leads) { var filter = document.getElementById(\'statusFilter\').value; var filtered = filter === \'all\' ? leads : leads.filter(function(l) { return l.status === filter; }); var container = document.getElementById(\'leadsList\'); if (filtered.length === 0) { container.innerHTML = \'<p style="text-align:center;color:#888;padding:2rem;">No leads match this filter.</p>\'; container.style.display = \'flex\'; return; } var html = \'\'; for (var i = 0; i < filtered.length; i++) { html += renderLeadCard(filtered[i]); } container.innerHTML = html; container.style.display = \'flex\'; }\n';
  html += '    async function loadLeads() { var loading = document.getElementById(\'loadingState\'); var authPrompt = document.getElementById(\'authPrompt\'); var errorState = document.getElementById(\'errorState\'); var emptyState = document.getElementById(\'emptyState\'); var leadsList = document.getElementById(\'leadsList\'); loading.style.display = \'block\'; authPrompt.style.display = \'none\'; errorState.style.display = \'none\'; emptyState.style.display = \'none\'; leadsList.style.display = \'none\'; try { var token = localStorage.getItem(\'token\'); if (!token) { loading.style.display = \'none\'; authPrompt.style.display = \'block\'; return; } var response = await fetch(API_BASE + \'/api/chef/leads\', { headers: { \'Authorization\': \'Bearer \' + token } }); if (response.status === 401) { loading.style.display = \'none\'; authPrompt.style.display = \'block\'; return; } if (!response.ok) { throw new Error(\'Failed to fetch leads\'); } var leads = await response.json(); currentLeads = leads; loading.style.display = \'none\'; if (!leads || leads.length === 0) { emptyState.style.display = \'block\'; return; } updateStats(leads); renderLeads(leads); leadsList.style.display = \'flex\'; } catch (err) { console.error(\'Error loading leads:\', err); loading.style.display = \'none\'; errorState.style.display = \'block\'; document.getElementById(\'errorMessage\').textContent = err.message || \'Unable to load leads.\'; } }\n';
  html += '    async function openLeadDetail(leadId) { currentLeadId = leadId; var token = localStorage.getItem(\'token\'); try { var response = await fetch(API_BASE + \'/api/chef/leads/\' + leadId, { headers: { \'Authorization\': \'Bearer \' + token } }); if (!response.ok) { alert(\'Failed to load lead details\'); return; } var lead = await response.json(); showLeadModal(lead); } catch (err) { alert(\'Error loading lead: \' + err.message); } }\n';
  html += '    function buildModalBody(lead) { var dietaryTags = lead.serviceDietaryTags || []; var dietaryHtml = \'\'; if (dietaryTags.length > 0) { dietaryHtml = \'<p style="margin-bottom:1rem;"><strong>Dietary tags:</strong> <span style="background:#f0f8e8;color:#2d5a0b;padding:0.2rem 0.6rem;border-radius:12px;font-size:0.8rem;margin-left:0.5rem;">\' + dietaryTags.join(\', \') + \'</span></p>\'; } var phoneHtml = lead.phone ? \'<br><span style="color:#888;\">\' + escapeHtml(lead.phone) + \'</span>\' : \'\'; var pricePerPersonHtml = lead.servicePricePerPerson ? \'<div class="lead-detail-item"><div class="lead-detail-label">Listed Price</div><div class="lead-detail-value">$\' + Number(lead.servicePricePerPerson).toFixed(0) + \'/person</div></div>\' : \'\'; var quotePreviewHtml = \'\'; if (lead.status === \'responded\' && lead.quoteAmount) { quotePreviewHtml = \'<div class="quote-preview"><strong>Quote Sent:</strong> $\' + Number(lead.quoteAmount).toFixed(2) + (lead.quoteMessage ? \'<br><em>\' + escapeHtml(lead.quoteMessage) + \'</em>\' : \'\') + \'</div>\'; } var messageHtml = lead.message ? \'<div class="lead-message"><strong>Message:</strong><p style="margin-top:0.4rem;\">\' + escapeHtml(lead.message) + \'</p></div>\' : \'<div class="lead-message"><strong>Message:</strong><p style="color:#aaa;margin-top:0.4rem;font-style:italic;">No message included</p></div>\'; var guestCount = lead.guestCount || 0; return \'<div class="lead-detail-grid">\' + \'<div class="lead-detail-item"><div class="lead-detail-label">Service</div><div class="lead-detail-value">\' + escapeHtml(lead.serviceName || \'\') + \'</div></div>\' + \'<div class="lead-detail-item"><div class="lead-detail-label">Guests</div><div class="lead-detail-value">\' + guestCount + \'</div></div>\' + \'<div class="lead-detail-item"><div class="lead-detail-label">Event Date</div><div class="lead-detail-value">\' + formatEventDate(lead.eventDate) + \'</div></div>\' + \'<div class="lead-detail-item"><div class="lead-detail-label">Contact</div><div class="lead-detail-value">\' + escapeHtml(lead.email) + phoneHtml + \'</div></div>\' + pricePerPersonHtml + \'<div class="lead-detail-item"><div class="lead-detail-label">Guest Count Range</div><div class="lead-detail-value">\' + (lead.serviceMinGuests || 1) + \'-\' + (lead.serviceMaxGuests || 10) + \' guests</div></div>\' + \'</div>\' + dietaryHtml + messageHtml + quotePreviewHtml; }\n';
  html += '    function buildModalFooter(lead) { var actions = \'\'; if (lead.status === \'new\' || lead.status === \'responded\') { actions += \'<button class="btn btn-success" onclick="sendQuote()">Send Quote</button>\'; } if (lead.status === \'responded\') { actions += \'<button class="btn btn-success" onclick="updateLeadStatus(\' + lead.id + \', &apos;converted&apos;)">Mark Converted</button>\'; actions += \'<button class="btn btn-danger" onclick="updateLeadStatus(\' + lead.id + \', &apos;lost&apos;)">Mark Lost</button>\'; } if (lead.status === \'new\') { actions += \'<button class="btn btn-danger" onclick="updateLeadStatus(\' + lead.id + \', &apos;lost&apos;)">Mark Lost</button>\'; } return actions; }\n';
  html += '    function buildQuoteSection(lead) { var sectionTitle = lead.status === \'new\' ? \'Send Price Quote\' : \'Edit Quote\'; return \'<div class="quote-section"><h3>\' + sectionTitle + \'</h3>\' + \'<div id="quoteSuccessMsg" class="success-msg" style="display:none">Quote sent successfully!</div>\' + \'<div class="form-group"><label for="quoteAmount">Total Price ($)</label>\' + \'<input type="number" id="quoteAmount" placeholder="e.g. 450.00" min="0" step="0.01" value="\' + (lead.quoteAmount || \'\') + \'">\' + \'</div>\' + \'<div class="form-group"><label for="quoteMessage">Message to Diner (optional)</label>\' + \'<textarea id="quoteMessage" placeholder="Include details about dietary accommodations, menu, etc.">\' + (lead.quoteMessage || \'\') + \'</textarea>\' + \'</div></div>\'; }\n';
  html += '    function showLeadModal(lead) { document.getElementById(\'modalLeadName\').textContent = lead.clientName || \'Guest\'; var statusEl = document.getElementById(\'modalStatus\'); statusEl.className = \'status-badge status-\' + lead.status; statusEl.textContent = lead.status.charAt(0).toUpperCase() + lead.status.slice(1); var bodyHtml = buildModalBody(lead); if (lead.status === \'new\' || lead.status === \'responded\') { bodyHtml += buildQuoteSection(lead); } document.getElementById(\'modalBody\').innerHTML = bodyHtml; document.getElementById(\'modalFooter\').innerHTML = buildModalFooter(lead); document.getElementById(\'leadModal\').classList.add(\'open\'); }\n';
  html += '    async function sendQuote() { var amount = document.getElementById(\'quoteAmount\').value; var message = document.getElementById(\'quoteMessage\').value; var token = localStorage.getItem(\'token\'); var body = {}; if (amount) body.quoteAmount = parseFloat(amount); if (message) body.quoteMessage = message; try { var response = await fetch(API_BASE + \'/api/chef/leads/\' + currentLeadId + \'/respond\', { method: \'POST\', headers: { \'Authorization\': \'Bearer \' + token, \'Content-Type\': \'application/json\' }, body: JSON.stringify(body) }); if (!response.ok) { var err = await response.json(); alert(\'Error: \' + (err.error || \'Failed to send quote\')); return; } var successMsg = document.getElementById(\'quoteSuccessMsg\'); if (successMsg) { successMsg.style.display = \'block\'; } loadLeads(); } catch (err) { alert(\'Error sending quote: \' + err.message); } }\n';
  html += '    async function updateLeadStatus(leadId, status) { if (!confirm(\'Mark this lead as \' + status + \'?\')) return; var token = localStorage.getItem(\'token\'); try { var response = await fetch(API_BASE + \'/api/chef/leads/\' + leadId + \'/status\', { method: \'POST\', headers: { \'Authorization\': \'Bearer \' + token, \'Content-Type\': \'application/json\' }, body: JSON.stringify({ status: status }) }); if (!response.ok) { alert(\'Failed to update status\'); return; } closeModal(); loadLeads(); } catch (err) { alert(\'Error updating status: \' + err.message); } }\n';
  html += '    function closeModal() { document.getElementById(\'leadModal\').classList.remove(\'open\'); currentLeadId = null; }\n';
  html += '    document.getElementById(\'leadModal\').addEventListener(\'click\', function(e) { if (e.target === this) closeModal(); });\n';
  html += '    loadLeads();\n';
  html += '  </script>\n';
  html += '</body>\n';
  html += '</html>\n';
  return html;
}
