// Chef Dashboard Page (MAI-2062)
// Shows overview with pending leads banner

export default function buildChefDashboardPage(): string {
  var html = '';
  html += '<!DOCTYPE html>\n';
  html += '<html lang="en">\n';
  html += '<head>\n';
  html += '<meta charset="UTF-8">\n';
  html += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  html += '<title>Chef Dashboard | Maison des Chefs</title>\n';
  html += '<style>\n';
  html += '    * { margin: 0; padding: 0; box-sizing: border-box; }\n';
  html += '    body { font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f8f9fa; }\n';
  html += '    nav { position: fixed; top: 0; left: 0; right: 0; background: rgba(0,0,0,0.9); padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; z-index: 100; backdrop-filter: blur(10px); }\n';
  html += '    nav .logo { color: white; font-size: 1.5rem; font-weight: bold; text-decoration: none; }\n';
  html += '    nav .nav-links { display: flex; gap: 1.5rem; }\n';
  html += '    nav .nav-links a { color: white; text-decoration: none; transition: opacity 0.3s; }\n';
  html += '    nav .nav-links a:hover { opacity: 0.8; }\n';
  html += '    nav .nav-links a.active { opacity: 0.8; border-bottom: 2px solid #c9a227; }\n';
  html += '    .bell-btn { background: none; border: none; cursor: pointer; position: relative; padding: 0.5rem; display: flex; align-items: center; }\n';
  html += '    .bell-btn svg { width: 22px; height: 22px; fill: white; transition: opacity 0.2s; }\n';
  html += '    .bell-btn:hover svg { opacity: 0.7; }\n';
  html += '    .bell-badge { position: absolute; top: 0px; right: 0px; background: #e74c3c; color: white; font-size: 0.65rem; font-weight: 700; min-width: 16px; height: 16px; border-radius: 8px; display: flex; align-items: center; justify-content: center; padding: 0 4px; }\n';
  html += '    .notification-dropdown { position: absolute; top: calc(100% + 8px); right: 0; width: 340px; background: white; border-radius: 12px; box-shadow: 0 8px 32px rgba(0,0,0,0.2); z-index: 200; display: none; overflow: hidden; }\n';
  html += '    .notification-dropdown.open { display: block; }\n';
  html += '    .notification-dropdown-header { padding: 0.75rem 1rem; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; align-items: center; }\n';
  html += '    .notification-dropdown-header span { font-weight: 600; color: #2c3e50; font-size: 0.9rem; }\n';
  html += '    .mark-all-read-btn { background: none; border: none; color: #c9a227; font-size: 0.8rem; cursor: pointer; font-weight: 600; }\n';
  html += '    .mark-all-read-btn:hover { text-decoration: underline; }\n';
  html += '    .notification-list { max-height: 320px; overflow-y: auto; }\n';
  html += '    .notification-item { padding: 0.85rem 1rem; border-bottom: 1px solid #f0f0f0; cursor: pointer; transition: background 0.15s; }\n';
  html += '    .notification-item:hover { background: #f8f9fa; }\n';
  html += '    .notification-item:last-child { border-bottom: none; }\n';
  html += '    .notification-item.unread { background: #fafafa; }\n';
  html += '    .notification-item.unread .notif-title { font-weight: 700; }\n';
  html += '    .notif-title { font-size: 0.92rem; color: #2c3e50; margin-bottom: 0.2rem; }\n';
  html += '    .notif-body { font-size: 0.82rem; color: #666; margin-bottom: 0.2rem; line-height: 1.4; }\n';
  html += '    .notif-time { font-size: 0.72rem; color: #999; }\n';
  html += '    .notif-icon { width: 30px; height: 30px; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; margin-right: 0.6rem; font-size: 0.9rem; flex-shrink: 0; }\n';
  html += '    .notif-icon-new_lead { background: #e3f2fd; }\n';
  html += '    .notif-icon-booking_confirmed { background: #d4edda; }\n';
  html += '    .notif-icon-booking_declined { background: #f8d7da; }\n';
  html += '    .notif-icon-review_request { background: #fff3cd; }\n';
  html += '    .notif-row { display: flex; align-items: flex-start; }\n';
  html += '    .notif-content { flex: 1; }\n';
  html += '    .notif-empty { padding: 1.5rem; text-align: center; color: #999; font-size: 0.9rem; }\n';
  html += '    @media (max-width: 640px) { .notification-dropdown { width: calc(100vw - 2rem); right: -1rem; } }\n';
  html += '    .page-header { background: linear-gradient(135deg, #2c3e50 0%, #1a252f 100%); padding: 7rem 2rem 2.5rem; color: white; }\n';
  html += '    .page-header-inner { max-width: 1100px; margin: 0 auto; display: flex; justify-content: space-between; align-items: center; }\n';
  html += '    .page-header h1 { font-size: clamp(1.8rem, 4vw, 2.5rem); margin-bottom: 0.3rem; }\n';
  html += '    .page-header p { opacity: 0.9; font-size: 1rem; }\n';
  html += '    .btn { display: inline-block; background: #c9a227; color: white; padding: 0.75rem 1.5rem; text-decoration: none; border-radius: 4px; font-weight: 600; transition: background 0.2s; border: none; cursor: pointer; font-size: 0.95rem; }\n';
  html += '    .btn:hover { background: #b8922a; }\n';
  html += '    .btn-secondary { background: #6c757d; }\n';
  html += '    .btn-secondary:hover { background: #5a6268; }\n';
  html += '    .btn-sm { padding: 0.4rem 0.9rem; font-size: 0.85rem; }\n';
  html += '    .btn-success { background: #27ae60; }\n';
  html += '    .btn-success:hover { background: #219a52; }\n';
  html += '    .dashboard-container { max-width: 1100px; margin: 2rem auto; padding: 0 2rem; }\n';
  html += '    .alert-banner { background: linear-gradient(135deg, #f39c12 0%, #e67e22 100%); color: white; padding: 1rem 1.5rem; border-radius: 8px; margin-bottom: 1.5rem; display: flex; align-items: center; gap: 1rem; font-size: 0.95rem; box-shadow: 0 4px 12px rgba(230, 126, 34, 0.3); }\n';
  html += '    .alert-banner.hidden { display: none; }\n';
  html += '    .alert-banner-close { background: none; border: none; color: white; font-size: 1.2rem; cursor: pointer; margin-left: auto; padding: 0; opacity: 0.8; line-height: 1; min-height: auto; min-width: auto; }\n';
  html += '    .alert-banner-close:hover { opacity: 1; }\n';
  html += '    .alert-banner-text { flex: 1; }\n';
  html += '    .alert-banner-btn { background: white; color: #e67e22; border: none; padding: 0.5rem 1rem; border-radius: 4px; font-size: 0.9rem; font-weight: 600; cursor: pointer; white-space: nowrap; }\n';
  html += '    .alert-banner-btn:hover { background: #fff5e6; }\n';
  html += '    .stats-row { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }\n';
  html += '    .stat-card { background: white; padding: 1.5rem; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); text-align: center; }\n';
  html += '    .stat-card .stat-icon { font-size: 2rem; margin-bottom: 0.5rem; }\n';
  html += '    .stat-value { font-size: 2.2rem; font-weight: 700; color: #2c3e50; }\n';
  html += '    .stat-label { font-size: 0.9rem; color: #888; margin-top: 0.25rem; }\n';
  html += '    .stat-card a { text-decoration: none; }\n';
  html += '    .stat-card:hover .stat-card-inner { transform: translateY(-2px); }\n';
  html += '    .stat-card-inner { transition: transform 0.2s; }\n';
  html += '    .quick-actions { background: white; padding: 1.5rem; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); margin-bottom: 2rem; }\n';
  html += '    .quick-actions h2 { font-size: 1.2rem; color: #2c3e50; margin-bottom: 1rem; }\n';
  html += '    .quick-actions-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; }\n';
  html += '    .quick-action-card { display: flex; align-items: center; gap: 1rem; padding: 1rem; border: 1.5px solid #eee; border-radius: 8px; text-decoration: none; color: inherit; transition: all 0.2s; }\n';
  html += '    .quick-action-card:hover { border-color: #c9a227; background: #fff9e6; }\n';
  html += '    .quick-action-icon { font-size: 1.5rem; flex-shrink: 0; }\n';
  html += '    .quick-action-text strong { display: block; color: #2c3e50; font-size: 1rem; margin-bottom: 0.2rem; }\n';
  html += '    .quick-action-text span { font-size: 0.85rem; color: #888; }\n';
  html += '    .loading-state { text-align: center; padding: 4rem 2rem; }\n';
  html += '    .loading-state .spinner { width: 48px; height: 48px; border: 4px solid #f3f3f3; border-top: 4px solid #c9a227; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 1rem; }\n';
  html += '    @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }\n';
  html += '    .auth-prompt { text-align: center; padding: 4rem 2rem; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }\n';
  html += '    .auth-prompt h2 { margin-bottom: 0.5rem; color: #2c3e50; }\n';
  html += '    .auth-prompt p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    footer { background: #1a1a1a; color: white; padding: 2rem; text-align: center; margin-top: 4rem; }\n';
  html += '    footer .logo { font-size: 1.3rem; font-weight: bold; margin-bottom: 0.5rem; }\n';
  html += '    footer p { opacity: 0.7; font-size: 0.85rem; }\n';
  html += '    @media (max-width: 768px) { .page-header-inner { flex-direction: column; align-items: flex-start; gap: 1rem; } .stats-row { grid-template-columns: 1fr 1fr; } }\n';
  html += '  </style>\n';
  html += '</head>\n';
  html += '<body>\n';
  html += '<nav>\n';
  html += '  <a href="/" class="logo">Maison des Chefs</a>\n';
  html += '  <div class="nav-links">\n';
  html += '    <a href="/chef/dashboard" class="active">Dashboard</a>\n';
  html += '    <a href="/chef/profile">My Profile</a>\n';
  html += '    <a href="/chef/leads">My Leads</a>\n';
  html += '    <a href="/chef/bookings">My Bookings</a>\n';
  html += '    <a href="/services">Services</a>\n';
  html += '    <a href="/auth/login">Sign In</a>\n';
  html += '    <button class="bell-btn" id="bellBtn" onclick="toggleNotifDropdown(event)" style="display:none;"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"/></svg><span class="bell-badge" id="bellBadge" style="display:none;">0</span></button>\n';
  html += '  </div>\n';
  html += '</nav>\n';
  html += '<div class="notification-dropdown" id="notifDropdown">\n';
  html += '  <div class="notification-dropdown-header"><span>Notifications</span><button class="mark-all-read-btn" onclick="markAllRead(event)">Mark all read</button></div>\n';
  html += '  <div class="notification-list" id="dropdownNotifList"><div class="notif-empty">Loading...</div></div>\n';
  html += '</div>\n';
  html += '<section class="page-header">\n';
  html += '  <div class="page-header-inner">\n';
  html += '    <div>\n';
  html += '      <h1>Chef Dashboard</h1>\n';
  html += '      <p>Welcome back — here is what is happening with your services</p>\n';
  html += '    </div>\n';
  html += '  </div>\n';
  html += '</section>\n';
  html += '<div class="dashboard-container">\n';
  html += '  <div id="pendingLeadsBanner" class="alert-banner hidden">\n';
  html += '    <span style="font-size:1.5rem;">&#9888;&#65039;</span>\n';
  html += '    <div class="alert-banner-text" id="bannerText"></div>\n';
  html += '    <button class="alert-banner-btn" id="bannerBtn" onclick="navigateToLeads()">Respond Now &#8594;</button>\n';
  html += '    <button class="alert-banner-close" onclick="dismissBanner()" title="Dismiss">&#215;</button>\n';
  html += '  </div>\n';
  html += '  <div id="loadingState" class="loading-state"><div class="spinner"></div><p>Loading dashboard...</p></div>\n';
  html += '  <div id="authPrompt" class="auth-prompt" style="display:none">\n';
  html += '    <h2>Sign In Required</h2>\n';
  html += '    <p>Please sign in to access your dashboard.</p>\n';
  html += '    <a href="/auth/login" class="btn">Sign In</a>\n';
  html += '  </div>\n';
  html += '  <div id="dashboardContent" style="display:none">\n';
  html += '    <div class="stats-row" id="statsRow"></div>\n';
  html += '    <div class="quick-actions">\n';
  html += '      <h2>Quick Actions</h2>\n';
  html += '      <div class="quick-actions-grid">\n';
  html += '        <a href="/chef/leads" class="quick-action-card">\n';
  html += '          <span class="quick-action-icon">&#128172;</span>\n';
  html += '          <div class="quick-action-text"><strong>View Leads</strong><span>Respond to diner inquiries</span></div>\n';
  html += '        </a>\n';
  html += '        <a href="/chef/bookings" class="quick-action-card">\n';
  html += '          <span class="quick-action-icon">&#128197;</span>\n';
  html += '          <div class="quick-action-text"><strong>My Bookings</strong><span>Manage upcoming events</span></div>\n';
  html += '        </a>\n';
  html += '        <a href="/chef/profile" class="quick-action-card">\n';
  html += '          <span class="quick-action-icon">&#128100;</span>\n';
  html += '          <div class="quick-action-text"><strong>My Profile</strong><span>Update your chef profile</span></div>\n';
  html += '        </a>\n';
  html += '        <a href="/services" class="quick-action-card">\n';
  html += '          <span class="quick-action-icon">&#127869;</span>\n';
  html += '          <div class="quick-action-text"><strong>Browse Services</strong><span>Explore other chefs</span></div>\n';
  html += '        </a>\n';
  html += '      </div>\n';
  html += '    </div>\n';
  html += '  </div>\n';
  html += '</div>\n';
  html += '<footer><div class="logo">Maison des Chefs</div><p>&copy; 2026 Maison des Chefs. All rights reserved.</p></footer>\n';
  html += '<script>\n';
  html += '    var API_BASE = \'\';\n';
  html += '    var bannerDismissed = false;\n';
  html += '    function escapeHtml(text) { if (!text) return \'\'; var div = document.createElement(\'div\'); div.textContent = text; return div.innerHTML; }\n';
  html += '    function navigateToLeads() { window.location.href = \'/chef/leads\'; }\n';
  html += '    function dismissBanner() { bannerDismissed = true; document.getElementById(\'pendingLeadsBanner\').classList.add(\'hidden\'); }\n';
  html += '    function renderStats(stats) {\n';
  html += '      var statsRow = document.getElementById(\'statsRow\');\n';
  html += '      statsRow.innerHTML = \n';
  html += '        \'<a href="/chef/leads" class="stat-card"><div class="stat-card-inner"><div class="stat-icon">&#128172;</div><div class="stat-value">\' + stats.newLeads + \'</div><div class="stat-label">New Leads</div></div></a>\' +\n';
  html += '        \'<a href="/chef/leads" class="stat-card"><div class="stat-card-inner"><div class="stat-icon">&#128221;</div><div class="stat-value">\' + stats.respondedLeads + \'</div><div class="stat-label">Awaiting Response</div></div></a>\' +\n';
  html += '        \'<a href="/chef/bookings" class="stat-card"><div class="stat-card-inner"><div class="stat-icon">&#128197;</div><div class="stat-value">\' + stats.upcomingBookings + \'</div><div class="stat-label">Upcoming Bookings</div></div></a>\' +\n';
  html += '        \'<div class="stat-card"><div class="stat-card-inner"><div class="stat-icon">&#9733;</div><div class="stat-value">\' + (stats.avgRating ? stats.avgRating.toFixed(1) : \'—\') + \'</div><div class="stat-label\">Avg Rating</div></div></div>\';\n';
  html += '    }\n';
  html += '    async function loadDashboard() {\n';
  html += '      var loading = document.getElementById(\'loadingState\');\n';
  html += '      var authPrompt = document.getElementById(\'authPrompt\');\n';
  html += '      var dashboardContent = document.getElementById(\'dashboardContent\');\n';
  html += '      var banner = document.getElementById(\'pendingLeadsBanner\');\n';
  html += '      loading.style.display = \'block\';\n';
  html += '      authPrompt.style.display = \'none\';\n';
  html += '      dashboardContent.style.display = \'none\';\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        if (!token) { loading.style.display = \'none\'; authPrompt.style.display = \'block\'; return; }\n';
  html += '        // Load pending leads count for banner\n';
  html += '        var statsRes = await fetch(API_BASE + \'/api/chef/leads/dashboard/stats\', { headers: { \'Authorization\': \'Bearer \' + token } });\n';
  html += '        if (statsRes.status === 401) { loading.style.display = \'none\'; authPrompt.style.display = \'block\'; return; }\n';
  html += '        var statsData = statsRes.ok ? await statsRes.json() : { pendingLeads: 0 };\n';
  html += '        var pendingLeads = statsData.pendingLeads || 0;\n';
  html += '        // Load additional stats (mock for now — leads count from leads page as proxy)\n';
  html += '        var leadsRes = await fetch(API_BASE + \'/api/chef/leads\', { headers: { \'Authorization\': \'Bearer \' + token } });\n';
  html += '        var allLeads = leadsRes.ok ? await leadsRes.json() : [];\n';
  html += '        var newLeads = allLeads.filter(function(l) { return l.status === \'new\'; }).length;\n';
  html += '        var respondedLeads = allLeads.filter(function(l) { return l.status === \'responded\'; }).length;\n';
  html += '        loading.style.display = \'none\';\n';
  html += '        dashboardContent.style.display = \'block\';\n';
  html += '        renderStats({ newLeads: newLeads, respondedLeads: respondedLeads, upcomingBookings: 0, avgRating: null });\n';
  html += '        // Show pending leads banner if applicable\n';
  html += '        if (pendingLeads > 0 && !bannerDismissed) {\n';
  html += '          var bannerText = document.getElementById(\'bannerText\');\n';
  html += '          bannerText.innerHTML = \'<strong>You have \' + pendingLeads + \' pending booking request\' + (pendingLeads !== 1 ? \'s\' : \'\') + \'</strong> &#8212; Respond now to keep your response rate high.\';\n';
  html += '          banner.classList.remove(\'hidden\');\n';
  html += '        }\n';
  html += '      } catch (err) {\n';
  html += '        console.error(\'Error loading dashboard:\', err);\n';
  html += '        loading.style.display = \'none\';\n';
  html += '        dashboardContent.style.display = \'block\';\n';
  html += '        renderStats({ newLeads: 0, respondedLeads: 0, upcomingBookings: 0, avgRating: null });\n';
  html += '      }\n';
  html += '    }\n';
  html += '    loadDashboard();\n';
  html += ' \n';
  html += '    // MAI-1700: Notification bell + dropdown\n';
  html += '    var notifPollInterval = null;\n';
  html += '    function notifFormatTime(dateStr) {\n';
  html += '      if (!dateStr) return \'\';\n';
  html += '      var date = new Date(dateStr);\n';
  html += '      var now = new Date();\n';
  html += '      var diff = now - date;\n';
  html += '      var minutes = Math.floor(diff / 60000);\n';
  html += '      var hours = Math.floor(diff / 3600000);\n';
  html += '      var days = Math.floor(diff / 86400000);\n';
  html += '      if (minutes < 1) return \'Just now\';\n';
  html += '      if (minutes < 60) return minutes + \'m ago\';\n';
  html += '      if (hours < 24) return hours + \'h ago\';\n';
  html += '      if (days < 7) return days + \'d ago\';\n';
  html += '      return date.toLocaleDateString(\'en-US\', { month: \'short\', day: \'numeric\' });\n';
  html += '    }\n';
  html += '    function notifGetIcon(type) {\n';
  html += '      if (type === \'new_lead\') return \'<div class="notif-icon notif-icon-new_lead">&#128172;</div>\';\n';
  html += '      if (type === \'booking_confirmed\') return \'<div class="notif-icon notif-icon-booking_confirmed">&#10003;</div>\';\n';
  html += '      if (type === \'booking_declined\') return \'<div class="notif-icon notif-icon-booking_declined">&#10005;</div>\';\n';
  html += '      if (type === \'review_request\') return \'<div class="notif-icon notif-icon-review_request">&#9733;</div>\';\n';
  html += '      return \'<div class="notif-icon notif-icon-new_lead">&#8226;</div>\';\n';
  html += '    }\n';
  html += '    function notifEscapeHtml(text) {\n';
  html += '      if (!text) return \'\';\n';
  html += '      var div = document.createElement(\'div\');\n';
  html += '      div.textContent = text;\n';
  html += '      return div.innerHTML;\n';
  html += '    }\n';
  html += '    function notifRenderItem(n) {\n';
  html += '      var unreadClass = n.read ? \'\' : \'unread\';\n';
  html += '      return \'<div class="notification-item \' + unreadClass + \'" onclick="notifHandleClick(event, \' + n.id + \', \' + JSON.stringify(n.metadata || {}).replace(/\'/g, "\\\'") + \')">\' +\n';
  html += '        \'<div class="notif-row">\' + notifGetIcon(n.type) +\n';
  html += '        \'<div class="notif-content">\' +\n';
  html += '        \'<div class="notif-title">\' + notifEscapeHtml(n.title) + \'</div>\' +\n';
  html += '        \'<div class="notif-body">\' + notifEscapeHtml(n.body) + \'</div>\' +\n';
  html += '        \'<div class="notif-time">\' + notifFormatTime(n.createdAt) + \'</div></div></div></div>\';\n';
  html += '    }\n';
  html += '    function notifHandleClick(e, id, metadata) {\n';
  html += '      e.stopPropagation();\n';
  html += '      notifMarkRead(id);\n';
  html += '      if (metadata && metadata.leadId) {\n';
  html += '        closeNotifDropdown();\n';
  html += '        window.location.href = \'/chef/leads\';\n';
  html += '      }\n';
  html += '    }\n';
  html += '    async function notifMarkRead(id) {\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        await fetch(\'/api/chef/notifications/\' + id + \'/read\', {\n';
  html += '          method: \'PATCH\',\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token }\n';
  html += '        });\n';
  html += '        loadNotifBadge();\n';
  html += '      } catch (err) { console.error(\'Error marking read:\', err); }\n';
  html += '    }\n';
  html += '    async function notifMarkAllRead(e) {\n';
  html += '      e.stopPropagation();\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        await fetch(\'/api/chef/notifications/mark-all-read\', {\n';
  html += '          method: \'POST\',\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token }\n';
  html += '        });\n';
  html += '        loadNotifDropdown();\n';
  html += '        loadNotifBadge();\n';
  html += '      } catch (err) { console.error(\'Error marking all read:\', err); }\n';
  html += '    }\n';
  html += '    function markAllRead(e) { notifMarkAllRead(e); }\n';
  html += '    function toggleNotifDropdown(e) {\n';
  html += '      e.stopPropagation();\n';
  html += '      var dropdown = document.getElementById(\'notifDropdown\');\n';
  html += '      if (dropdown.classList.contains(\'open\')) {\n';
  html += '        closeNotifDropdown();\n';
  html += '      } else {\n';
  html += '        dropdown.classList.add(\'open\');\n';
  html += '        loadNotifDropdown();\n';
  html += '      }\n';
  html += '    }\n';
  html += '    function closeNotifDropdown() {\n';
  html += '      document.getElementById(\'notifDropdown\').classList.remove(\'open\');\n';
  html += '    }\n';
  html += '    async function loadNotifDropdown() {\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        if (!token) return;\n';
  html += '        var response = await fetch(\'/api/chef/notifications?limit=10&unreadOnly=false\', {\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token }\n';
  html += '        });\n';
  html += '        if (!response.ok) return;\n';
  html += '        var data = await response.json();\n';
  html += '        var list = document.getElementById(\'dropdownNotifList\');\n';
  html += '        var notifs = data.notifications || [];\n';
  html += '        if (notifs.length === 0) {\n';
  html += '          list.innerHTML = \'<div class="notif-empty">No notifications yet</div>\';\n';
  html += '        } else {\n';
  html += '          list.innerHTML = notifs.map(notifRenderItem).join(\'\');\n';
  html += '        }\n';
  html += '      } catch (err) { console.error(\'Error loading dropdown:\', err); }\n';
  html += '    }\n';
  html += '    async function loadNotifBadge() {\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        if (!token) return;\n';
  html += '        var response = await fetch(\'/api/chef/notifications?limit=1&unreadOnly=true\', {\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token }\n';
  html += '        });\n';
  html += '        if (!response.ok) return;\n';
  html += '        var data = await response.json();\n';
  html += '        var count = data.unread_count || 0;\n';
  html += '        var badge = document.getElementById(\'bellBadge\');\n';
  html += '        var bellBtn = document.getElementById(\'bellBtn\');\n';
  html += '        if (badge && bellBtn) {\n';
  html += '          if (count > 0) {\n';
  html += '            badge.textContent = count > 9 ? \'9+\' : count;\n';
  html += '            badge.style.display = \'flex\';\n';
  html += '            bellBtn.style.display = \'flex\';\n';
  html += '          } else {\n';
  html += '            badge.style.display = \'none\';\n';
  html += '          }\n';
  html += '        }\n';
  html += '      } catch (err) { console.error(\'Error loading badge:\', err); }\n';
  html += '    }\n';
  html += '    function startNotifPolling() {\n';
  html += '      loadNotifBadge();\n';
  html += '      notifPollInterval = setInterval(loadNotifBadge, 30000);\n';
  html += '    }\n';
  html += '    document.addEventListener(\'click\', function(e) {\n';
  html += '      var dropdown = document.getElementById(\'notifDropdown\');\n';
  html += '      var bellBtn = document.getElementById(\'bellBtn\');\n';
  html += '      if (dropdown && !dropdown.contains(e.target) && (!bellBtn || !bellBtn.contains(e.target))) {\n';
  html += '        dropdown.classList.remove(\'open\');\n';
  html += '      }\n';
  html += '    });\n';
  html += '    startNotifPolling();\n';
  html += '  </script>\n';
  html += '</body>\n';
  html += '</html>\n';
  return html;
}