// Chef Bookings Dashboard Page (MAI-1159 Task 2)
// Shows all bookings with accept/decline functionality

export default function buildChefBookingsPage(): string {
  var html = '';
  html += '<!DOCTYPE html>\n';
  html += '<html lang="en">\n';
  html += '<head>\n';
  html += '<meta charset="UTF-8">\n';
  html += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  html += '<title>My Bookings | Chef Dashboard</title>\n';
  html += '<style>\n';
  html += '    * { margin: 0; padding: 0; box-sizing: border-box; }\n';
  html += '    body { font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f8f9fa; }\n';
  html += '    nav { position: fixed; top: 0; left: 0; right: 0; background: rgba(0,0,0,0.9); padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; z-index: 100; backdrop-filter: blur(10px); }\n';
  html += '    nav .logo { color: white; font-size: 1.5rem; font-weight: bold; text-decoration: none; }\n';
  html += '    nav .nav-links { display: flex; gap: 1.5rem; }\n';
  html += '    nav .nav-links a { color: white; text-decoration: none; transition: opacity 0.3s; }\n';
  html += '    nav .nav-links a.active { opacity: 0.8; border-bottom: 2px solid #c9a227; }\n';
  html += '    nav .nav-links a:hover { opacity: 0.8; }\n';
  html += '    .page-header { background: linear-gradient(135deg, #2c3e50 0%, #1a252f 100%); padding: 7rem 2rem 2.5rem; color: white; }\n';
  html += '    .page-header-inner { max-width: 1100px; margin: 0 auto; display: flex; justify-content: space-between; align-items: center; }\n';
  html += '    .page-header h1 { font-size: clamp(1.8rem, 4vw, 2.5rem); margin-bottom: 0.3rem; }\n';
  html += '    .page-header p { opacity: 0.9; font-size: 1rem; }\n';
  html += '    .btn { display: inline-block; background: #c9a227; color: white; padding: 0.75rem 1.5rem; text-decoration: none; border-radius: 4px; font-weight: 600; transition: background 0.2s; border: none; cursor: pointer; font-size: 0.95rem; }\n';
  html += '    .btn:hover { background: #b8922a; }\n';
  html += '    .btn-secondary { background: #6c757d; }\n';
  html += '    .btn-secondary:hover { background: #5a6268; }\n';
  html += '    .btn-sm { padding: 0.4rem 0.9rem; font-size: 0.85rem; }\n';
  html += '    .btn-success { background: #27ae60; }\n';
  html += '    .btn-success:hover { background: #219a52; }\n';
  html += '    .btn-danger { background: #c0392b; }\n';
  html += '    .btn-danger:hover { background: #a93226; }\n';
  html += '    .bookings-container { max-width: 1100px; margin: 2rem auto; padding: 0 2rem; }\n';
  html += '    .stats-row { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin-bottom: 2rem; }\n';
  html += '    .stat-card { background: white; padding: 1.25rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); text-align: center; }\n';
  html += '    .stat-value { font-size: 2rem; font-weight: 700; color: #2c3e50; }\n';
  html += '    .stat-label { font-size: 0.85rem; color: #888; margin-top: 0.25rem; }\n';
  html += '    .filter-bar { background: white; padding: 1rem 1.5rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); margin-bottom: 1.5rem; display: flex; gap: 1rem; align-items: center; flex-wrap: wrap; }\n';
  html += '    .filter-bar label { font-weight: 500; color: #555; font-size: 0.9rem; }\n';
  html += '    .filter-bar select { padding: 0.4rem 0.75rem; border: 1px solid #ddd; border-radius: 4px; font-size: 0.9rem; }\n';
  html += '    .bookings-list { display: flex; flex-direction: column; gap: 1rem; }\n';
  html += '    .booking-card { background: white; padding: 1.25rem 1.5rem; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); display: flex; justify-content: space-between; align-items: center; gap: 1rem; }\n';
  html += '    .booking-card-main { flex: 1; }\n';
  html += '    .booking-card-header { display: flex; align-items: center; gap: 0.75rem; margin-bottom: 0.4rem; flex-wrap: wrap; }\n';
  html += '    .booking-name { font-size: 1.1rem; font-weight: 600; color: #2c3e50; }\n';
  html += '    .booking-service { color: #666; font-size: 0.9rem; margin-bottom: 0.4rem; }\n';
  html += '    .booking-meta { display: flex; gap: 1rem; color: #888; font-size: 0.85rem; flex-wrap: wrap; align-items: center; }\n';
  html += '    .booking-meta span { display: flex; align-items: center; gap: 0.25rem; }\n';
  html += '    .booking-card-actions { display: flex; align-items: center; gap: 0.75rem; flex-shrink: 0; flex-wrap: wrap; justify-content: flex-end; }\n';
  html += '    .status-badge { padding: 0.2rem 0.7rem; border-radius: 20px; font-size: 0.78rem; font-weight: 600; white-space: nowrap; }\n';
  html += '    .status-pending { background: #fff3cd; color: #856404; }\n';
  html += '    .status-confirmed { background: #d4edda; color: #155724; }\n';
  html += '    .status-declined, .status-rejected { background: #f8d7da; color: #721c24; }\n';
  html += '    .status-accepted { background: #d4edda; color: #155724; }\n';
  html += '    .loading-state, .error-state, .empty-state, .auth-prompt { text-align: center; padding: 4rem 2rem; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }\n';
  html += '    .loading-state .spinner { width: 48px; height: 48px; border: 4px solid #f3f3f3; border-top: 4px solid #c9a227; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 1rem; }\n';
  html += '    @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }\n';
  html += '    .error-state { color: #c0392b; }\n';
  html += '    .error-state h2 { margin-bottom: 0.5rem; }\n';
  html += '    .error-state p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    .empty-state h2 { color: #2c3e50; margin-bottom: 0.5rem; }\n';
  html += '    .empty-state p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    .auth-prompt h2 { margin-bottom: 0.5rem; color: #2c3e50; }\n';
  html += '    .auth-prompt p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    .confirm-dialog-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.6); z-index: 200; display: none; align-items: center; justify-content: center; padding: 1rem; }\n';
  html += '    .confirm-dialog-overlay.open { display: flex; }\n';
  html += '    .confirm-dialog { background: white; border-radius: 12px; width: 100%; max-width: 440px; padding: 1.5rem; box-shadow: 0 8px 32px rgba(0,0,0,0.2); }\n';
  html += '    .confirm-dialog h3 { color: #2c3e50; margin-bottom: 0.75rem; font-size: 1.15rem; }\n';
  html += '    .confirm-dialog p { color: #555; margin-bottom: 1.25rem; font-size: 0.95rem; }\n';
  html += '    .confirm-dialog-actions { display: flex; justify-content: flex-end; gap: 0.75rem; }\n';
  html += '    .toast { position: fixed; bottom: 2rem; right: 2rem; padding: 1rem 1.5rem; border-radius: 8px; font-weight: 500; z-index: 300; box-shadow: 0 4px 16px rgba(0,0,0,0.2); transition: opacity 0.3s; }\n';
  html += '    .toast.success { background: #27ae60; color: white; }\n';
  html += '    .toast.error { background: #c0392b; color: white; }\n';
  html += '    footer { background: #1a1a1a; color: white; padding: 2rem; text-align: center; margin-top: 4rem; }\n';
  html += '    footer .logo { font-size: 1.3rem; font-weight: bold; margin-bottom: 0.5rem; }\n';
  html += '    footer p { opacity: 0.7; font-size: 0.85rem; }\n';
  html += '    @media (max-width: 768px) { .page-header-inner { flex-direction: column; align-items: flex-start; gap: 1rem; } .booking-card { flex-direction: column; align-items: flex-start; } .booking-card-actions { width: 100%; justify-content: flex-end; } }\n';
  html += '  </style>\n';
  html += '</head>\n';
  html += '<body>\n';
  html += '<nav>\n';
  html += '  <a href="/" class="logo">Maison des Chefs</a>\n';
  html += '  <div class="nav-links">\n';
  html += '    <a href="/chef/profile">My Profile</a>\n';
  html += '    <a href="/chef/leads">My Leads</a>\n';
  html += '    <a href="/chef/bookings" class="active">My Bookings</a>\n';
  html += '    <a href="/services">Services</a>\n';
  html += '    <a href="/auth/login">Sign In</a>\n';
  html += '  </div>\n';
  html += '</nav>\n';
  html += '<section class="page-header">\n';
  html += '  <div class="page-header-inner">\n';
  html += '    <div>\n';
  html += '      <h1>My Bookings</h1>\n';
  html += '      <p>Accept or decline diner booking requests</p>\n';
  html += '    </div>\n';
  html += '  </div>\n';
  html += '</section>\n';
  html += '<div class="bookings-container">\n';
  html += '  <div class="stats-row" id="statsRow">\n';
  html += '    <div class="stat-card"><div class="stat-value" id="statPending">-</div><div class="stat-label">Pending</div></div>\n';
  html += '    <div class="stat-card"><div class="stat-value" id="statConfirmed">-</div><div class="stat-label">Confirmed</div></div>\n';
  html += '    <div class="stat-card"><div class="stat-value" id="statDeclined">-</div><div class="stat-label">Declined</div></div>\n';
  html += '    <div class="stat-card"><div class="stat-value" id="statTotal">-</div><div class="stat-label">Total</div></div>\n';
  html += '  </div>\n';
  html += '  <div class="filter-bar">\n';
  html += '    <label>Filter by status:</label>\n';
  html += '    <select id="statusFilter" onchange="renderBookings(currentBookings)">\n';
  html += '      <option value="all">All Bookings</option>\n';
  html += '      <option value="pending">Pending</option>\n';
  html += '      <option value="confirmed">Confirmed</option>\n';
  html += '      <option value="accepted">Accepted</option>\n';
  html += '      <option value="declined">Declined</option>\n';
  html += '      <option value="rejected">Rejected</option>\n';
  html += '    </select>\n';
  html += '  </div>\n';
  html += '  <div id="loadingState" class="loading-state"><div class="spinner"></div><p>Loading your bookings...</p></div>\n';
  html += '  <div id="authPrompt" class="auth-prompt" style="display:none"><h2>Sign In Required</h2><p>Please sign in to view your bookings.</p><a href="/auth/login" class="btn">Sign In</a></div>\n';
  html += '  <div id="errorState" class="error-state" style="display:none"><h2>Something went wrong</h2><p id="errorMessage">Unable to load bookings.</p><button class="btn" onclick="loadBookings()">Try Again</button></div>\n';
  html += '  <div id="emptyState" class="empty-state" style="display:none"><h2>No bookings yet</h2><p>When diners book your services, they will appear here.</p></div>\n';
  html += '  <div id="bookingsList" class="bookings-list" style="display:none"></div>\n';
  html += '</div>\n';
  html += '<div class="confirm-dialog-overlay" id="confirmDialog">\n';
  html += '  <div class="confirm-dialog">\n';
  html += '    <h3 id="confirmTitle">Confirm Action</h3>\n';
  html += '    <p id="confirmMessage">Are you sure?</p>\n';
  html += '    <div class="confirm-dialog-actions">\n';
  html += '      <button class="btn btn-secondary" onclick="closeConfirmDialog()">Cancel</button>\n';
  html += '      <button class="btn" id="confirmBtn" onclick="confirmAction()">Confirm</button>\n';
  html += '    </div>\n';
  html += '  </div>\n';
  html += '</div>\n';
  html += '<div id="toast" class="toast" style="display:none"></div>\n';
  html += '<footer><div class="logo">Maison des Chefs</div><p>&copy; 2026 Maison des Chefs. All rights reserved.</p></footer>\n';
  html += '<script>\n';
  html += '    var API_BASE = \'\';\n';
  html += '    var BOOKINGS_API = \'/bookings\';\n';
  html += '    var currentBookings = [];\n';
  html += '    var pendingAction = null;\n';
  html += '    function escapeHtml(text) { if (!text) return \'\'; var div = document.createElement(\'div\'); div.textContent = text; return div.innerHTML; }\n';
  html += '    function formatDate(dateStr) { if (!dateStr) return \'Flexible date\'; try { return new Date(dateStr).toLocaleDateString(\'en-US\', { month: \'short\', day: \'numeric\', year: \'numeric\' }); } catch(e) { return dateStr; } }\n';
  html += '    function formatEventDate(dateStr) { if (!dateStr) return \'Flexible\'; try { return new Date(dateStr).toLocaleDateString(\'en-US\', { weekday: \'short\', month: \'short\', day: \'numeric\', year: \'numeric\' }); } catch(e) { return dateStr; } }\n';
  html += '    function showToast(message, type) { var toast = document.getElementById(\'toast\'); toast.textContent = message; toast.className = \'toast \' + type; toast.style.display = \'block\'; setTimeout(function() { toast.style.opacity = \'0\'; setTimeout(function() { toast.style.display = \'none\'; toast.style.opacity = \'1\'; }, 300); }, 3000); }\n';
  html += '    function updateStats(bookings) { var counts = { pending: 0, confirmed: 0, accepted: 0, declined: 0, rejected: 0 }; for (var i = 0; i < bookings.length; i++) { var s = bookings[i].status; if (counts[s] !== undefined) counts[s]++; } document.getElementById(\'statPending\').textContent = counts.pending; document.getElementById(\'statConfirmed\').textContent = counts.confirmed + counts.accepted; document.getElementById(\'statDeclined\').textContent = counts.declined + counts.rejected; document.getElementById(\'statTotal\').textContent = bookings.length; }\n';
  html += '    function getStatusClass(status) { var map = { pending: \'status-pending\', confirmed: \'status-confirmed\', accepted: \'status-accepted\', declined: \'status-declined\', rejected: \'status-rejected\' }; return map[status] || \'status-pending\'; }\n';
  html += '    function getStatusLabel(status) { var labels = { pending: \'Pending\', confirmed: \'Confirmed\', accepted: \'Accepted\', declined: \'Declined\', rejected: \'Rejected\' }; return labels[status] || status.charAt(0).toUpperCase() + status.slice(1); }\n';
  html += '    function renderBookingCard(booking) { var statusClass = getStatusClass(booking.status); var statusLabel = getStatusLabel(booking.status); var guestCount = booking.guestCount || 0; var notesHtml = booking.notes ? \'<div style="color:#666;font-size:0.85rem;margin-top:0.3rem;"><em>\"\' + escapeHtml(booking.notes) + \'\"</em></div>\' : \'\'; var actionsHtml = \'\'; if (booking.status === \'pending\') { actionsHtml += \'<button class="btn btn-success btn-sm" onclick="openConfirmDialog(\' + booking.id + \', \'accept\')">Accept</button>\'; actionsHtml += \'<button class="btn btn-danger btn-sm" onclick="openConfirmDialog(\' + booking.id + \', \'decline\')">Decline</button>\'; } return \'<div class="booking-card\">\' + \'<div class="booking-card-main">\' + \'<div class="booking-card-header">\' + \'<span class="booking-name">\' + escapeHtml(booking.dinerName || \'Guest\') + \'</span>\' + \'<span class="status-badge \' + statusClass + \'">\' + statusLabel + \'</span>\' + \'</div>\' + \'<div class="booking-service">\' + escapeHtml(booking.serviceName || \'—\') + \' — $\' + Number(booking.totalPrice || 0).toFixed(0) + \' total</div>\' + notesHtml + \'<div class="booking-meta">\' + \'<span>📅 \' + formatEventDate(booking.eventDate) + \'</span>\' + \'<span>👥 \' + guestCount + \' guest\' + (guestCount !== 1 ? \'s\' : \'\') + \'</span>\' + \'<span>✉️ \' + escapeHtml(booking.dinerEmail || booking.email || \'—\') + \'</span>\' + \'</div>\' + \'</div>\' + \'<div class="booking-card-actions\">\' + actionsHtml + \'</div>\' + \'</div>\'; }\n';
  html += '    function renderBookings(bookings) { var filter = document.getElementById(\'statusFilter\').value; var filtered = filter === \'all\' ? bookings : bookings.filter(function(b) { return b.status === filter; }); var container = document.getElementById(\'bookingsList\'); if (filtered.length === 0) { container.innerHTML = \'<p style="text-align:center;color:#888;padding:2rem;\">No bookings match this filter.</p>\'; container.style.display = \'flex\'; return; } var html = \'\'; for (var i = 0; i < filtered.length; i++) { html += renderBookingCard(filtered[i]); } container.innerHTML = html; container.style.display = \'flex\'; }\n';
  html += '    async function loadBookings() { var loading = document.getElementById(\'loadingState\'); var authPrompt = document.getElementById(\'authPrompt\'); var errorState = document.getElementById(\'errorState\'); var emptyState = document.getElementById(\'emptyState\'); var bookingsList = document.getElementById(\'bookingsList\'); loading.style.display = \'block\'; authPrompt.style.display = \'none\'; errorState.style.display = \'none\'; emptyState.style.display = \'none\'; bookingsList.style.display = \'none\'; try { var token = localStorage.getItem(\'token\'); if (!token) { loading.style.display = \'none\'; authPrompt.style.display = \'block\'; return; } var response = await fetch(BOOKINGS_API, { headers: { \'Authorization\': \'Bearer \' + token } }); if (response.status === 401) { loading.style.display = \'none\'; authPrompt.style.display = \'block\'; return; } if (!response.ok) { throw new Error(\'Failed to fetch bookings\'); } var bookings = await response.json(); currentBookings = bookings; loading.style.display = \'none\'; if (!bookings || bookings.length === 0) { emptyState.style.display = \'block\'; return; } updateStats(bookings); renderBookings(bookings); bookingsList.style.display = \'flex\'; } catch (err) { console.error(\'Error loading bookings:\', err); loading.style.display = \'none\'; errorState.style.display = \'block\'; document.getElementById(\'errorMessage\').textContent = err.message || \'Unable to load bookings.\'; } }\n';
  html += '    function openConfirmDialog(bookingId, action) { pendingAction = { bookingId: bookingId, action: action }; var title = document.getElementById(\'confirmTitle\'); var message = document.getElementById(\'confirmMessage\'); var btn = document.getElementById(\'confirmBtn\'); if (action === \'accept\') { title.textContent = \'Accept Booking?\'; message.textContent = \'This will confirm the booking for the diner. They will be notified by email.\'; btn.className = \'btn btn-success\'; btn.textContent = \'Accept\'; } else { title.textContent = \'Decline Booking?\'; message.textContent = \'This will decline the booking. The diner will be notified and can book with another chef.\'; btn.className = \'btn btn-danger\'; btn.textContent = \'Decline\'; } document.getElementById(\'confirmDialog\').classList.add(\'open\'); }\n';
  html += '    function closeConfirmDialog() { document.getElementById(\'confirmDialog\').classList.remove(\'open\'); pendingAction = null; }\n';
  html += '    async function confirmAction() { if (!pendingAction) return; var bookingId = pendingAction.bookingId; var action = pendingAction.action; closeConfirmDialog(); var token = localStorage.getItem(\'token\'); var newStatus = action === \'accept\' ? \'confirmed\' : \'rejected\'; try { var response = await fetch(BOOKINGS_API + \'/\' + bookingId + \'/status\', { method: \'PATCH\', headers: { \'Authorization\': \'Bearer \' + token, \'Content-Type\': \'application/json\' }, body: JSON.stringify({ status: newStatus }) }); if (!response.ok) { var errData = await response.json().catch(function() { return {} }); throw new Error(errData.error || \'Failed to update booking\'); } showToast(action === \'accept\' ? \'Booking accepted!\' : \'Booking declined.\', \'success\'); loadBookings(); } catch (err) { showToast(err.message || \'Error updating booking\', \'error\'); } }\n';
  html += '    document.getElementById(\'confirmDialog\').addEventListener(\'click\', function(e) { if (e.target === this) closeConfirmDialog(); });\n';
  html += '    loadBookings();\n';
  html += '  </script>\n';
  html += '</body>\n';
  html += '</html>\n';
  return html;
}