// Chef Date-Specific Availability Slots Page (MAI-2625)
// Route: /chef/availability/slots
// Allows chefs to add/remove date-specific availability slots for booking inquiries

export function buildChefDateAvailabilityPage(): string {
  var html = '';
  html += '<!DOCTYPE html>\n';
  html += '<html lang="en">\n';
  html += '<head>\n';
  html += '<meta charset="UTF-8">\n';
  html += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  html += '<title>Availability Slots | Maison des Chefs</title>\n';
  html += '<style>\n';
  html += '    * { margin: 0; padding: 0; box-sizing: border-box; }\n';
  html += '    body { font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, sans-serif; line-height: 1.6; color: #333; background: #f8f9fa; }\n';
  html += '    nav { position: fixed; top: 0; left: 0; right: 0; background: rgba(0,0,0,0.9); padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; z-index: 100; backdrop-filter: blur(10px); }\n';
  html += '    nav .logo { color: white; font-size: 1.5rem; font-weight: bold; text-decoration: none; }\n';
  html += '    nav .nav-links { display: flex; gap: 1.5rem; }\n';
  html += '    nav .nav-links a { color: white; text-decoration: none; transition: opacity 0.3s; }\n';
  html += '    nav .nav-links a:hover { opacity: 0.8; }\n';
  html += '    nav .nav-links a.active { opacity: 0.8; border-bottom: 2px solid #c9a227; }\n';
  html += '    .page-header { background: linear-gradient(135deg, #2c3e50 0%, #1a252f 100%); padding: 6rem 2rem 2rem; color: white; }\n';
  html += '    .page-header h1 { font-size: clamp(1.8rem, 4vw, 2.2rem); margin-bottom: 0.3rem; }\n';
  html += '    .page-header p { opacity: 0.85; font-size: 0.95rem; max-width: 600px; }\n';
  html += '    .page-header .info-badge { display: inline-flex; align-items: center; gap: 0.5rem; background: rgba(255,255,255,0.15); padding: 0.5rem 1rem; border-radius: 20px; font-size: 0.85rem; margin-top: 1rem; }\n';
  html += '    .slots-container { max-width: 900px; margin: 2rem auto; padding: 0 2rem 4rem; }\n';
  html += '    .slots-card { background: white; border-radius: 12px; padding: 2rem; box-shadow: 0 2px 8px rgba(0,0,0,0.06); margin-bottom: 1.5rem; }\n';
  html += '    .slots-card h2 { font-size: 1.2rem; color: #2c3e50; margin-bottom: 0.25rem; }\n';
  html += '    .slots-card p { color: #888; font-size: 0.88rem; margin-bottom: 1.5rem; }\n';
  html += '    .add-slot-form { display: grid; grid-template-columns: 1fr 1fr 1fr auto; gap: 0.75rem; align-items: flex-end; flex-wrap: wrap; }\n';
  html += '    .add-slot-form .form-group { margin: 0; flex: 1; min-width: 140px; }\n';
  html += '    .add-slot-form label { display: block; font-size: 0.82rem; color: #888; margin-bottom: 0.3rem; font-weight: 500; }\n';
  html += '    .add-slot-form input[type="date"], .add-slot-form input[type="time"] { width: 100%; padding: 0.6rem 0.75rem; border: 1px solid #ddd; border-radius: 6px; font-size: 0.9rem; }\n';
  html += '    .add-slot-form button { padding: 0.6rem 1.2rem; background: #c9a227; color: white; border: none; border-radius: 6px; font-size: 0.9rem; font-weight: 600; cursor: pointer; transition: background 0.2s; white-space: nowrap; }\n';
  html += '    .add-slot-form button:hover { background: #b8922a; }\n';
  html += '    .add-slot-form button:disabled { background: #ccc; cursor: not-allowed; }\n';
  html += '    .slots-list { margin-top: 1.5rem; }\n';
  html += '    .slot-item { display: flex; align-items: center; justify-content: space-between; padding: 0.85rem 1rem; background: #f8f9fa; border-radius: 8px; margin-bottom: 0.6rem; flex-wrap: wrap; gap: 0.5rem; }\n';
  html += '    .slot-item.booked { background: #fff3cd; border: 1px solid #ffc107; }\n';
  html += '    .slot-info { display: flex; align-items: center; gap: 1rem; flex-wrap: wrap; }\n';
  html += '    .slot-date { font-weight: 600; color: #2c3e50; font-size: 0.95rem; min-width: 120px; }\n';
  html += '    .slot-time { font-size: 0.9rem; color: #666; }\n';
  html += '    .slot-status { display: inline-flex; align-items: center; gap: 0.3rem; font-size: 0.78rem; padding: 0.25rem 0.6rem; border-radius: 12px; font-weight: 600; }\n';
  html += '    .slot-status.available { background: #d4edda; color: #155724; }\n';
  html += '    .slot-status.booked { background: #fff3cd; color: #856404; }\n';
  html += '    .slot-remove { background: none; border: 1px solid #e74c3c; color: #e74c3c; padding: 0.3rem 0.75rem; border-radius: 4px; font-size: 0.8rem; cursor: pointer; font-weight: 500; transition: all 0.2s; }\n';
  html += '    .slot-remove:hover:not(:disabled) { background: #e74c3c; color: white; }\n';
  html += '    .slot-remove:disabled { opacity: 0.4; cursor: not-allowed; border-color: #ccc; color: #ccc; }\n';
  html += '    .slot-empty { text-align: center; padding: 2rem; color: #aaa; font-size: 0.9rem; background: #f8f9fa; border-radius: 8px; }\n';
  html += '    .slot-empty-icon { font-size: 2.5rem; margin-bottom: 0.5rem; }\n';
  html += '    .btn { display: inline-block; background: #c9a227; color: white; padding: 0.85rem 2rem; text-decoration: none; border-radius: 6px; font-weight: 600; transition: background 0.2s; border: none; cursor: pointer; font-size: 1rem; }\n';
  html += '    .btn:hover { background: #b8922a; }\n';
  html += '    .toast { position: fixed; bottom: 2rem; right: 2rem; padding: 1rem 1.5rem; border-radius: 8px; font-size: 0.92rem; font-weight: 500; box-shadow: 0 4px 16px rgba(0,0,0,0.15); z-index: 1000; transform: translateY(100px); opacity: 0; transition: all 0.3s; }\n';
  html += '    .toast.success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }\n';
  html += '    .toast.error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }\n';
  html += '    .toast.visible { transform: translateY(0); opacity: 1; }\n';
  html += '    .loading-state, .auth-prompt { text-align: center; padding: 4rem 2rem; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }\n';
  html += '    .loading-state .spinner { width: 48px; height: 48px; border: 4px solid #f3f3f3; border-top: 4px solid #c9a227; border-radius: 50%; animation: spin 1s linear infinite; margin: 0 auto 1rem; }\n';
  html += '    @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }\n';
  html += '    .auth-prompt h2 { margin-bottom: 0.5rem; color: #2c3e50; }\n';
  html += '    .auth-prompt p { color: #666; margin-bottom: 1.5rem; }\n';
  html += '    footer { background: #1a1a1a; color: white; padding: 2rem; text-align: center; margin-top: 4rem; }\n';
  html += '    footer .logo { font-size: 1.3rem; font-weight: bold; margin-bottom: 0.5rem; }\n';
  html += '    footer p { opacity: 0.7; font-size: 0.85rem; }\n';
  html += '    @media (max-width: 640px) { .add-slot-form { grid-template-columns: 1fr 1fr; } .add-slot-form .form-group:last-child { grid-column: 1 / -1; } .slot-item { flex-direction: column; align-items: flex-start; } .slot-remove { width: 100%; } }\n';
  html += '  </style>\n';
  html += '</head>\n';
  html += '<body>\n';
  html += '<nav>\n';
  html += '  <a href="/" class="logo">Maison des Chefs</a>\n';
  html += '  <div class="nav-links">\n';
  html += '    <a href="/chef/dashboard">Dashboard</a>\n';
  html += '    <a href="/chef/profile">My Profile</a>\n';
  html += '    <a href="/chef/leads">My Leads</a>\n';
  html += '    <a href="/chef/bookings">My Bookings</a>\n';
  html += '    <a href="/chef/availability/slots" class="active">Availability Slots</a>\n';
  html += '  </div>\n';
  html += '</nav>\n';
  html += '<section class="page-header">\n';
  html += '  <h1>Availability Slots</h1>\n';
  html += '  <p>Add specific dates and times when you are available to accept booking inquiries. Diners can only book during these slots.</p>\n';
  html += '  <div class="info-badge"><span>&#9432;</span> Without availability slots, diners cannot successfully submit booking requests.</div>\n';
  html += '</section>\n';
  html += '<div class="slots-container">\n';
  html += '  <div id="loadingState" class="loading-state"><div class="spinner"></div><p>Loading availability slots...</p></div>\n';
  html += '  <div id="authPrompt" class="auth-prompt" style="display:none">\n';
  html += '    <h2>Sign In Required</h2>\n';
  html += '    <p>Please sign in to manage your availability slots.</p>\n';
  html += '    <a href="/auth/login" class="btn">Sign In</a>\n';
  html += '  </div>\n';
  html += '  <div id="slotsContent" style="display:none">\n';
  html += '    <div class="slots-card">\n';
  html += '      <h2>Add Availability Slot</h2>\n';
  html += '      <p>Select a date and time range for your availability. Overlapping slots will be rejected.</p>\n';
  html += '      <div class="add-slot-form">\n';
  html += '        <div class="form-group">\n';
  html += '          <label for="slotDateInput">Date</label>\n';
  html += '          <input type="date" id="slotDateInput" min="' + new Date().toISOString().split('T')[0] + '">\n';
  html += '        </div>\n';
  html += '        <div class="form-group">\n';
  html += '          <label for="slotStartTimeInput">Start Time</label>\n';
  html += '          <input type="time" id="slotStartTimeInput" value="18:00">\n';
  html += '        </div>\n';
  html += '        <div class="form-group">\n';
  html += '          <label for="slotEndTimeInput">End Time</label>\n';
  html += '          <input type="time" id="slotEndTimeInput" value="21:00">\n';
  html += '        </div>\n';
  html += '        <button onclick="addSlot()" id="addSlotBtn">Add Slot +</button>\n';
  html += '      </div>\n';
  html += '    </div>\n';
  html += '    <div class="slots-card">\n';
  html += '      <h2>Your Availability Slots</h2>\n';
  html += '      <p>Slots with a booking cannot be removed. Booked slots are shown in yellow.</p>\n';
  html += '      <div id="slotsList" class="slots-list"></div>\n';
  html += '    </div>\n';
  html += '  </div>\n';
  html += '</div>\n';
  html += '<div id="toast" class="toast"></div>\n';
  html += '<footer><div class="logo">Maison des Chefs</div><p>&copy; 2026 Maison des Chefs. All rights reserved.</p></footer>\n';
  html += '<script>\n';
  html += '    var API_BASE = \'\';\n';
  html += '    var slots = [];\n';
  html += '    var chefId = null;\n';
  html += '    var isAdding = false;\n';
  html += '    function escapeHtml(text) { if (!text) return \'\'; var div = document.createElement(\'div\'); div.textContent = text; return div.innerHTML; }\n';
  html += '    function showToast(message, type) {\n';
  html += '      var toast = document.getElementById(\'toast\');\n';
  html += '      toast.textContent = message;\n';
  html += '      toast.className = \'toast \' + type + \' visible\';\n';
  html += '      setTimeout(function() { toast.className = \'toast \' + type; }, 3500);\n';
  html += '    }\n';
  html += '    function formatDate(dateStr) {\n';
  html += '      var date = new Date(dateStr + \'T00:00:00\');\n';
  html += '      return date.toLocaleDateString(\'en-US\', { weekday: \'short\', year: \'numeric\', month: \'short\', day: \'numeric\' });\n';
  html += '    }\n';
  html += '    function formatTime(timeStr) {\n';
  html += '      if (!timeStr) return \'\';\n';
  html += '      var parts = timeStr.split(\':\');\n';
  html += '      var hour = parseInt(parts[0], 10);\n';
  html += '      var minute = parts[1];\n';
  html += '      var ampm = hour >= 12 ? \'PM\' : \'AM\';\n';
  html += '      hour = hour % 12;\n';
  html += '      if (hour === 0) hour = 12;\n';
  html += '      return hour + \':\' + minute + \' \' + ampm;\n';
  html += '    }\n';
  html += '    function renderSlots() {\n';
  html += '      var list = document.getElementById(\'slotsList\');\n';
  html += '      var sortedSlots = slots.slice().sort(function(a, b) {\n';
  html += '        if (a.date !== b.date) return a.date.localeCompare(b.date);\n';
  html += '        return a.start_time.localeCompare(b.start_time);\n';
  html += '      });\n';
  html += '      var today = new Date().toISOString().split(\'T\')[0];\n';
  html += '      var futureSlots = sortedSlots.filter(function(s) { return s.date >= today; });\n';
  html += '      var pastSlots = sortedSlots.filter(function(s) { return s.date < today; });\n';
  html += '      var html = \'\';\n';
  html += '      if (futureSlots.length === 0 && pastSlots.length === 0) {\n';
  html += '        html += \'<div class="slot-empty"><div class="slot-empty-icon">&#128197;</div><p>No availability slots yet. Add your first slot above!</p></div>\';\n';
  html += '      }\n';
  html += '      if (futureSlots.length > 0) {\n';
  html += '        html += \'<h3 style="font-size:0.9rem;color:#888;margin-bottom:0.75rem;">Upcoming Slots</h3>\';\n';
  html += '        for (var i = 0; i < futureSlots.length; i++) {\n';
  html += '          var slot = futureSlots[i];\n';
  html += '          var bookedClass = slot.is_booked ? \' booked\' : \'\';\n';
  html += '          var statusBadge = slot.is_booked \n';
  html += '            ? \'<span class="slot-status booked">&#10003; Booked</span>\' \n';
  html += '            : \'<span class="slot-status available">&#9679; Available</span>\';\n';
  html += '          html += \'<div class="slot-item\' + bookedClass + \'" data-id="\' + escapeHtml(slot.id) + \'">\';\n';
  html += '          html += \'  <div class="slot-info">\';\n';
  html += '            html += \'<span class="slot-date">\' + formatDate(slot.date) + \'</span>\';\n';
  html += '            html += \'<span class="slot-time">\' + formatTime(slot.start_time) + \' - \' + formatTime(slot.end_time) + \'</span>\';\n';
  html += '            html += statusBadge;\n';
  html += '          html += \'  </div>\';\n';
  html += '          if (!slot.is_booked) {\n';
  html += '            html += \'  <button class="slot-remove" onclick="removeSlot(\' + JSON.stringify(slot.id) + \')">Remove</button>\';\n';
  html += '          } else {\n';
  html += '            html += \'  <button class="slot-remove" disabled>Remove</button>\';\n';
  html += '          }\n';
  html += '          html += \'</div>\';\n';
  html += '        }\n';
  html += '      }\n';
  html += '      if (pastSlots.length > 0) {\n';
  html += '        html += \'<h3 style="font-size:0.9rem;color:#888;margin-bottom:0.75rem;margin-top:1.5rem;">Past Slots</h3>\';\n';
  html += '        for (var j = 0; j < pastSlots.length; j++) {\n';
  html += '          var slot = pastSlots[j];\n';
  html += '          html += \'<div class="slot-item" style="opacity:0.6;">\';\n';
  html += '          html += \'  <div class="slot-info">\';\n';
  html += '            html += \'<span class="slot-date">\' + formatDate(slot.date) + \'</span>\';\n';
  html += '            html += \'<span class="slot-time">\' + formatTime(slot.start_time) + \' - \' + formatTime(slot.end_time) + \'</span>\';\n';
  html += '            html += \'<span class="slot-status" style="background:#eee;color:#888;">Expired</span>\';\n';
  html += '          html += \'  </div>\';\n';
  html += '          html += \'</div>\';\n';
  html += '        }\n';
  html += '      }\n';
  html += '      list.innerHTML = html;\n';
  html += '    }\n';
  html += '    async function addSlot() {\n';
  html += '      if (isAdding) return;\n';
  html += '      var dateInput = document.getElementById(\'slotDateInput\');\n';
  html += '      var startInput = document.getElementById(\'slotStartTimeInput\');\n';
  html += '      var endInput = document.getElementById(\'slotEndTimeInput\');\n';
  html += '      var btn = document.getElementById(\'addSlotBtn\');\n';
  html += '      var date = dateInput.value;\n';
  html += '      var start_time = startInput.value;\n';
  html += '      var end_time = endInput.value;\n';
  html += '      if (!date) { showToast(\'Please select a date\', \'error\'); return; }\n';
  html += '      if (!start_time) { showToast(\'Please select a start time\', \'error\'); return; }\n';
  html += '      if (!end_time) { showToast(\'Please select an end time\', \'error\'); return; }\n';
  html += '      if (start_time >= end_time) { showToast(\'Start time must be before end time\', \'error\'); return; }\n';
  html += '      btn.disabled = true;\n';
  html += '      btn.textContent = \'Adding...\';\n';
  html += '      isAdding = true;\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        var res = await fetch(API_BASE + \'/api/availability\', {\n';
  html += '          method: \'POST\',\n';
  html += '          headers: { \'Content-Type\': \'application/json\', \'Authorization\': \'Bearer \' + token },\n';
  html += '          body: JSON.stringify({ date: date, start_time: start_time, end_time: end_time }),\n';
  html += '        });\n';
  html += '        var data = await res.json();\n';
  html += '        if (!res.ok) throw new Error(data.error || \'Failed to add slot\');\n';
  html += '        slots.push(data.slot);\n';
  html += '        renderSlots();\n';
  html += '        dateInput.value = \'\';\n';
  html += '        showToast(\'Availability slot added successfully\', \'success\');\n';
  html += '      } catch (err) {\n';
  html += '        showToast(err.message, \'error\');\n';
  html += '      } finally {\n';
  html += '        btn.disabled = false;\n';
  html += '        btn.textContent = \'Add Slot +\';\n';
  html += '        isAdding = false;\n';
  html += '      }\n';
  html += '    }\n';
  html += '    async function removeSlot(slotId) {\n';
  html += '      if (!confirm(\'Remove this availability slot? Diners will no longer be able to book during this time.\')) return;\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        var res = await fetch(API_BASE + \'/api/availability\', {\n';
  html += '          method: \'DELETE\',\n';
  html += '          headers: { \'Content-Type\': \'application/json\', \'Authorization\': \'Bearer \' + token },\n';
  html += '          body: JSON.stringify({ id: slotId }),\n';
  html += '        });\n';
  html += '        if (!res.ok) { var data = await res.json(); throw new Error(data.error || \'Failed to remove slot\'); }\n';
  html += '        var idx = slots.findIndex(function(s) { return s.id === slotId; });\n';
  html += '        if (idx >= 0) slots.splice(idx, 1);\n';
  html += '        renderSlots();\n';
  html += '        showToast(\'Slot removed\', \'success\');\n';
  html += '      } catch (err) {\n';
  html += '        showToast(err.message, \'error\');\n';
  html += '      }\n';
  html += '    }\n';
  html += '    async function loadSlots() {\n';
  html += '      try {\n';
  html += '        var token = localStorage.getItem(\'token\');\n';
  html += '        var today = new Date();\n';
  html += '        var endDate = new Date();\n';
  html += '        endDate.setDate(endDate.getDate() + 90);\n';
  html += '        var dateFrom = today.toISOString().split(\'T\')[0];\n';
  html += '        var dateTo = endDate.toISOString().split(\'T\')[0];\n';
  html += '        var res = await fetch(API_BASE + \'/api/availability?date_from=\' + dateFrom + \'&date_to=\' + dateTo, {\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token },\n';
  html += '        });\n';
  html += '        if (!res.ok) throw new Error(\'Failed to load slots\');\n';
  html += '        var data = await res.json();\n';
  html += '        slots = data.slots || [];\n';
  html += '      } catch (err) {\n';
  html += '        console.error(\'Error loading slots:\', err);\n';
  html += '        slots = [];\n';
  html += '      }\n';
  html += '    }\n';
  html += '    async function initPage() {\n';
  html += '      var token = localStorage.getItem(\'token\');\n';
  html += '      if (!token) {\n';
  html += '        document.getElementById(\'loadingState\').style.display = \'none\';\n';
  html += '        document.getElementById(\'authPrompt\').style.display = \'block\';\n';
  html += '        return;\n';
  html += '      }\n';
  html += '      try {\n';
  html += '        var profileRes = await fetch(API_BASE + \'/api/auth/me\', {\n';
  html += '          headers: { \'Authorization\': \'Bearer \' + token },\n';
  html += '        });\n';
  html += '        if (!profileRes.ok) throw new Error(\'Not authenticated\');\n';
  html += '        var profile = await profileRes.json();\n';
  html += '        chefId = profile.chefId || profile.id;\n';
  html += '        await loadSlots();\n';
  html += '        document.getElementById(\'loadingState\').style.display = \'none\';\n';
  html += '        document.getElementById(\'slotsContent\').style.display = \'block\';\n';
  html += '        renderSlots();\n';
  html += '      } catch (err) {\n';
  html += '        console.error(\'Error initializing page:\', err);\n';
  html += '        document.getElementById(\'loadingState\').innerHTML = \'<p>Failed to load. Please <a href="/auth/login">sign in</a> again.</p>\';\n';
  html += '      }\n';
  html += '    }\n';
  html += '    initPage();\n';
  html += '  <\/script>\n';
  html += '<\/body>\n';
  html += '<\/html>\n';
  return html;
}

export default buildChefDateAvailabilityPage;
